const ITEMS = [
  // ===== 写作与内容 (1-10) =====
  {id:1, title:"撰写论文和报告", subtitle:"AI帮你构建论点和研究", category:"writing",
    description:"AI可以帮助你整理思路、构建有力的论点，并撰写结构清晰的论文和报告。它不会替你写——但会帮你写得更好。用它来头脑风暴、创建大纲和润色草稿。",
    steps:["选择主题并将参考资料粘贴给AI","请AI帮助头脑风暴论点或论题","请求包含引言、正文段落和结论的大纲","用大纲写草稿，然后请AI审阅并提出改进建议"],
    prompt:"帮我写一篇关于[主题]的[文章类型：议论文/研究报告/分析报告]。\n\n首先帮我头脑风暴3个有力的论点来支持这个论题：[你的论题]。\n\n然后为一篇[字数]字的文章创建详细大纲，包含：\n- 引人入胜的引言和明确的论题陈述\n- 每个正文段落有主题句和论据\n- 预判反驳观点\n- 总结关键论点的结论\n\n学术水平：[初中/高中/大学]",
    promptTip:"永远不要直接提交AI生成的文字。用AI来帮助构建和改进你自己的想法。请AI对你的草稿提出'具体改进建议'，而不是重写。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"ChatGPT",url:"https://chat.openai.com"},{name:"Claude",url:"https://claude.ai"}]},

  {id:2, title:"创建博客和文章", subtitle:"为任何话题打造引人入胜的内容", category:"writing",
    description:"无论你是开始写博客还是为学校项目写作，AI都能帮你生成创意、创建大纲和撰写引人注目的内容。学习如何用AI增强你独特的声音。",
    steps:["确定你的话题和目标受众","请AI生成吸引人的标题和大纲","用你自己的声音写初稿","用AI润色、优化SEO并改进可读性"],
    prompt:"帮我为[目标受众]创建一篇关于[主题]的博客文章。文章应该是[语气：有趣的/专业的/随意的/教育性的]。\n\n请提供：\n1. 5个吸引人的标题选项\n2. 带副标题的详细大纲\n3. 引人入胜的开头段落\n4. 每个部分的要点\n5. 号召行动结尾\n\n目标字数：[字数]。包括让文章更易分享的建议。",
    promptTip:"最好的博客结合了AI的效率和你的个人经历。先写，然后用AI润色——而不是反过来。",
    tools:["ChatGPT","Claude","WordPress","Medium"],
    links:[{name:"WordPress",url:"https://wordpress.com"},{name:"Medium",url:"https://medium.com"}]},

  {id:3, title:"撰写创意故事", subtitle:"AI是你的写作合作伙伴", category:"writing",
    description:"AI是出色的创意写作搭档。用它来打破写作瓶颈、发展角色、构建情节，或共同创作整个故事。你引导创意方向，AI帮你实现愿景。",
    steps:["分享你的故事概念、类型和主要角色","请AI帮你发展情节结构","用AI对话来逐场景写作","请求对节奏、对话和描写的反馈"],
    prompt:"帮我写一个[类型：奇幻/科幻/悬疑/爱情/恐怖]短篇故事。\n\n设定：[描述世界/背景]\n主角：[姓名、年龄、关键特征]\n核心冲突：[主要问题或挑战]\n基调：[黑暗/轻松/悬疑/感人]\n\n先创建一个三幕情节大纲，然后写出引人入胜的开头场景（约[字数]字）。让它有生动的描写和自然的对话。",
    promptTip:"给AI具体的方向效果最好。与其说'写个故事'，不如描述你想要的语气、风格和情感冲击。用'继续写但增加更多悬念'来引导AI。",
    tools:["ChatGPT","Claude","NovelAI","Sudowrite"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:4, title:"掌握语法和校对", subtitle:"用AI超越拼写检查", category:"writing",
    description:"AI不仅仅是拼写检查器——它可以帮你理解语法规则、改善句子结构，并在保持你声音的同时使你的写作更加精炼。像拥有一个24/7可用的耐心英语老师。",
    steps:["将你的文字粘贴给AI","请求语法、清晰度和风格方面的反馈","请AI解释每个建议背后的原因","应用修改并从修正中学习"],
    prompt:"请审阅这段文字的语法、清晰度和风格：\n\n[粘贴你的文字]\n\n请：\n1. 修正任何语法或拼写错误\n2. 改善句子结构和流畅性\n3. 建议更有力的词汇选择\n4. 简明解释每个修改的原因\n5. 按当前写作水平评分（1-10）并提出改进建议\n\n保持我的原始声音和风格——只在需要的地方改进。",
    promptTip:"请AI'解释语法规则，而不只是修正'——这样你才能真正学到东西。试着请它在你的文字中找出'我可能没注意到的弱句子'。",
    tools:["ChatGPT","Claude","Grammarly","Hemingway Editor"],
    links:[{name:"Grammarly",url:"https://www.grammarly.com"},{name:"Hemingway Editor",url:"https://hemingwayapp.com"}]},

  {id:5, title:"翻译和学习语言", subtitle:"即时翻译与语言指导", category:"writing",
    description:"AI不仅仅翻译——它解释细微差别、文化背景和替代表达方式。用它来学习新语言或理解母语人士的真实表达。",
    steps:["请AI翻译文本或解释概念","询问字面翻译和自然表达之间的区别","练习对话并获得即时反馈","请求关于习语和文化背景的解释"],
    prompt:"将以下内容从[源语言]翻译为[目标语言]：\n\n[你的文字]\n\n请提供：\n1. 直接翻译\n2. 自然/地道的翻译\n3. 5个关键词汇及其发音和用法\n4. 需要注意的文化差异\n5. 在[目标语言]中表达同一意思的不同方式\n\n然后创建一个简短的练习对话，让我练习使用这些新词汇。",
    promptTip:"请AI充当语言伙伴：'我们用[语言]对话。纠正我的错误并解释如何改进。先从简单开始。'",
    tools:["ChatGPT","Claude","DeepL","Duolingo"],
    links:[{name:"DeepL",url:"https://www.deepl.com"},{name:"Duolingo",url:"https://www.duolingo.com"}]},

  {id:6, title:"写诗歌和歌词", subtitle:"与AI一起创作文学作品", category:"writing",
    description:"AI可以帮你探索诗歌形式、押韵方案和韵律模式。无论你是经验丰富的诗人还是初次尝试，AI都是出色的创作伙伴。",
    steps:["分享你的主题、情感或灵感","选择形式（自由诗、十四行诗、歌词等）","与AI协作起草和修改","用AI反馈调整节奏和意象"],
    prompt:"帮我写一首关于[主题/情感/体验]的[类型：诗歌/歌词/说唱/俳句/十四行诗]。\n\n情绪：[快乐/忧郁/怀旧/充满活力/沉思]\n风格灵感：[提及你喜欢的诗人/艺术家]\n\n请提供：\n1. 3种不同的第一段/节方案\n2. 隐喻和意象建议\n3. 如果合适，押韵方案选项\n4. 完整的草稿\n5. 修改技巧\n\n让它感觉真实和有情感，不要陈词滥调。",
    promptTip:"诗歌是协作使用AI的最佳领域之一。先分享你的原始想法或情感——AI可以帮你找到完美的词语来表达你已经感受到的东西。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"ChatGPT",url:"https://chat.openai.com"},{name:"RhymeZone",url:"https://www.rhymezone.com"}]},

  {id:7, title:"创建社交媒体内容", subtitle:"让帖子脱颖而出", category:"writing",
    description:"AI帮你创建引人注目的社交媒体内容——从字幕和话题标签到内容日历和营销策略。学习如何让帖子脱颖而出。",
    steps:["定义你的平台、受众和目标","请AI生成内容创意和字幕","创建一致的发布计划","分析有效的内容并调整策略"],
    prompt:"为[平台：Instagram/TikTok/Twitter/LinkedIn]创建一周的内容，主题是[话题/领域]。目标受众：[受众描述]。\n\n每天提供：\n1. 帖子概念和相关话题标签\n2. 引人注目的字幕（适合平台的长度）\n3. 互动文案（提问、投票、号召行动）\n4. 最佳发布时间建议\n5. 增加互动的技巧\n\n让语气[有趣/专业/教育性/鼓舞人心]且真实——不要感觉像企业营销。",
    promptTip:"最好的社交媒体内容是在分享价值，不是在推销。请AI帮你平衡——80%有价值的内容，20%推广。真实性比完美更重要。",
    tools:["ChatGPT","Claude","Canva","Buffer"],
    links:[{name:"Canva",url:"https://www.canva.com"},{name:"Buffer",url:"https://buffer.com"}]},

  {id:8, title:"制作简历和求职信", subtitle:"脱颖而出获得心仪职位", category:"writing",
    description:"AI帮你创建专业的简历和量身定制的求职信，突出你的优势并针对特定职位优化。就像有一个职业顾问全程指导。",
    steps:["分享你的经历、技能和目标职位","请AI构建你的简历","为每个申请量身定制求职信","请AI审阅并优化关键词"],
    prompt:"帮我创建/更新我的简历。背景：\n- 当前角色/状态：[学生/求职者/转行者]\n- 经验：[列出关键经历]\n- 技能：[你的技能]\n- 教育背景：[你的教育经历]\n- 目标职位：[你想申请什么]\n\n请：\n1. 提出最佳简历格式建议\n2. 用有力的动词写出有影响力的要点\n3. 量化成就\n4. 优化关键词以通过筛选\n5. 创建一封针对[具体职位]的求职信\n\n让它专业但有个性。",
    promptTip:"针对每份申请调整你的简历——用职位描述中的关键词。请AI'以招聘经理的角度审阅这份简历并指出弱点'。",
    tools:["ChatGPT","Claude","Canva","Overleaf"],
    links:[{name:"Canva简历模板",url:"https://www.canva.com/resumes"},{name:"Overleaf",url:"https://www.overleaf.com"}]},

  {id:9, title:"构建演示文稿", subtitle:"创建引人注目的幻灯片内容", category:"writing",
    description:"AI帮你构建演示文稿——从大纲到每张幻灯片的内容、演讲要点和视觉建议。不再有无聊的幻灯片！",
    steps:["定义你的话题、受众和时间限制","请AI创建演示结构和流程","为每张幻灯片编写内容和演讲备注","用AI建议添加视觉元素"],
    prompt:"帮我创建一个关于[话题]的[数量]张幻灯片演示文稿，面向[受众]。时间限制：[分钟]。\n\n每张幻灯片请提供：\n1. 幻灯片标题\n2. 关键要点（3-5个子弹点）\n3. 演讲备注（需要说的话）\n4. 视觉建议（图表/图片/图表类型）\n5. 过渡到下一张幻灯片\n\n开头要有力，中间有数据/故事支撑，结尾有明确的行动号召。让它引人入胜，不要信息过载。",
    promptTip:"每张幻灯片只表达一个核心观点。用10-20-30法则：10张幻灯片，20分钟，最小30号字体。先练习讲故事，不是读幻灯片。",
    tools:["ChatGPT","Claude","Gamma","Canva"],
    links:[{name:"Gamma",url:"https://gamma.app"},{name:"Canva演示文稿",url:"https://www.canva.com/presentations"}]},

  {id:10, title:"撰写邮件和消息", subtitle:"每次都能得到恰当的回复", category:"writing",
    description:"不确定怎么回复那封棘手的邮件？AI帮你撰写适合任何情境的邮件和消息——从专业的到个人的，从正式的到随意的。",
    steps:["描述情境和你想要的语气","分享你需要回复的邮件（如果有的话）","请AI起草多个版本","选择并个性化最佳版本"],
    prompt:"帮我写一封邮件。情境：[描述情境——向老师请假/跟进求职申请/解决客户投诉/邀请某人参加活动]。\n\n语气：[正式/半正式/友好/紧急]\n收件人：[谁]\n主要目的：[你想要什么结果]\n\n请提供：\n1. 吸引人的主题行\n2. 3个不同语气的版本\n3. 每个版本的优缺点\n4. 跟进邮件模板",
    promptTip:"在发送前一定要个性化AI生成的邮件。添加具体细节让它感觉真实。大声朗读——如果听起来像机器人就重写。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"ChatGPT",url:"https://chat.openai.com"},{name:"Claude",url:"https://claude.ai"}]},

  // ===== 学习与教育 (11-20) =====
  {id:11, title:"获得个性化辅导", subtitle:"随时可用的AI导师", category:"learning",
    description:"AI就像一个24/7可用、永不疲倦的私人导师。它可以用不同方式解释概念、创建练习题，并适应你的学习节奏。无论是数学、科学、历史还是任何科目。",
    steps:["告诉AI你在学什么以及你觉得困难的地方","请AI用多种方式解释概念","练习AI生成的习题","请求越来越难的挑战"],
    prompt:"做我的[科目]导师。我目前学到[话题/章节]。我的水平是[初学者/中级/高级]。\n\n请：\n1. 用简单的术语解释[概念]\n2. 给出3个现实生活中的例子\n3. 创建5个递增难度的练习题\n4. 在不给出答案的情况下检查我的答案——给我提示\n5. 根据我的错误建议我应该接下来学什么\n\n如果我困惑了，请用完全不同的方法解释。",
    promptTip:"最好的学习方式是先尝试后提问。先自己尝试解决问题，然后请AI解释你不理解的地方。请AI'用我能理解的方式解释'。",
    tools:["ChatGPT","Claude","Khan Academy","Wolfram Alpha"],
    links:[{name:"Khan Academy",url:"https://www.khanacademy.org"},{name:"Wolfram Alpha",url:"https://www.wolframalpha.com"}]},

  {id:12, title:"制作学习卡片", subtitle:"更聪明地复习，而不是更辛苦地复习", category:"learning",
    description:"间隔重复是经过科学验证的最有效学习方法之一。AI可以为任何科目创建完美的学习卡片——节省你数小时的准备时间。",
    steps:["分享你需要学习的话题或笔记","请AI创建问答对","导入到Anki或Quizlet等间隔重复应用","定期复习并请AI填补知识空白"],
    prompt:"为[科目/话题]创建[数量]张学习卡片。涵盖：[具体话题或章节]。\n\n每张卡片应有：\n- 正面：清晰的问题或提示\n- 背面：简洁的答案和简短解释\n- 难度标签（简单/中等/困难）\n\n包括：\n- 定义卡片\n- 概念应用卡片\n- 比较卡片（A与B对比）\n- 涵盖常见考试陷阱的卡片\n\n格式化以便于复制到Anki或Quizlet。",
    promptTip:"不要只是记忆——请AI创建测试理解而非回忆的卡片。'为什么X导致Y？'比'X的定义是什么？'更好。",
    tools:["ChatGPT","Claude","Anki","Quizlet"],
    links:[{name:"Anki",url:"https://apps.ankiweb.net"},{name:"Quizlet",url:"https://quizlet.com"}]},

  {id:13, title:"备考和练习", subtitle:"模拟考试和学习策略", category:"learning",
    description:"AI可以为任何科目创建逼真的模拟考试、练习题和学习计划。就像有一个了解考试内容的导师。",
    steps:["分享你在学什么以及考试格式","请AI创建模拟考试题","在计时条件下练习","复习答案并关注薄弱环节"],
    prompt:"帮我备考[科目/考试名称]。考试涵盖[话题列表]。格式：[选择题/简答题/论述题/混合]。\n\n请：\n1. 创建一个[数量]题的模拟考试\n2. 包含符合考试格式的不同题型\n3. 让题目涵盖从简单回忆到分析应用的范围\n4. 在答案中提供详细解释\n5. 根据错误模式推荐具体复习话题\n\n另外，创建一个考前最后一周的学习计划。",
    promptTip:"在考试日期前2-3周开始练习。请AI生成注重'为什么'而不只是'是什么'的题目——这是大多数考试实际测试的内容。",
    tools:["ChatGPT","Claude","Khan Academy","Quizlet"],
    links:[{name:"Khan Academy",url:"https://www.khanacademy.org"},{name:"Quizlet",url:"https://quizlet.com"}]},

  {id:14, title:"简化复杂话题", subtitle:"把任何东西变得容易理解", category:"learning",
    description:"AI擅长分解复杂话题。不管是量子物理、哲学还是经济学——AI可以把它解释得适合任何年龄水平。",
    steps:["分享你想理解的话题","指定你想要的理解水平","请AI使用类比和例子来解释","问后续问题直到完全理解"],
    prompt:"用[目标受众：10岁小孩/高中生/完全初学者]能理解的方式解释[复杂话题]。\n\n请：\n1. 从一个日常类比开始\n2. 逐步构建概念\n3. 使用视觉描述（'想象一下...'）\n4. 给出3个现实世界的例子\n5. 创建一个简单的测验来检验我的理解\n6. 列出关于这个话题的常见误解\n\n避免专业术语。如果你必须使用技术术语，立即用简单语言解释。",
    promptTip:"'用我是五岁小孩的方式解释'实际上是一种强大的学习技巧（费曼方法）。如果AI不能简单解释某件事，请它用不同的类比重试。",
    tools:["ChatGPT","Claude","Gemini","Perplexity"],
    links:[{name:"ChatGPT",url:"https://chat.openai.com"},{name:"Perplexity",url:"https://perplexity.ai"}]},

  {id:15, title:"学习编程", subtitle:"从零到编程英雄", category:"learning",
    description:"AI可能是有史以来最好的编程老师。它可以解释概念、编写和调试代码、创建练习，并根据你的进度调整——全部免费。",
    steps:["选择一门编程语言（推荐Python入门）","请AI创建个性化的学习路径","通过编写真实项目来学习","犯错时请AI解释并帮助调试"],
    prompt:"做我学习[编程语言：Python/JavaScript/HTML+CSS/Java]的编程导师。我是一个[水平：完全初学者/有一些经验/从另一门语言转来]。\n\n请：\n1. 创建一个4周的学习路线图\n2. 从一个简单有趣的项目开始\n3. 一次解释一个概念，并配有可运行的示例\n4. 给我练习（由简到难）\n5. 当我犯错时，在不直接给出答案的情况下引导我\n\n教学风格：[实践为主/理论在先/项目驱动]",
    promptTip:"学习编程的最好方法就是实际编写代码。不要只是读AI的解释——在repl.it或VS Code中输入代码并运行。犯错是学习过程的一部分！",
    tools:["ChatGPT","Claude","Replit","VS Code"],
    links:[{name:"Replit",url:"https://replit.com"},{name:"freeCodeCamp",url:"https://www.freecodecamp.org"}]},

  {id:16, title:"创建思维导图", subtitle:"视觉化组织你的思维", category:"learning",
    description:"思维导图帮助你看到不同想法之间的联系。AI可以从任何话题即时生成详细的思维导图——非常适合学习、头脑风暴和规划项目。",
    steps:["选择你想绘制思维导图的话题","请AI创建层次化的思维导图结构","使用免费工具可视化它","扩展你觉得有趣的分支"],
    prompt:"为[话题]创建一个详细的思维导图。中心主题：[主要概念]。\n\n请提供：\n1. 4-6个主要分支（关键类别）\n2. 每个分支3-4个子话题\n3. 主要分支之间的联系\n4. 颜色编码建议\n5. 关键事实或统计数据的注释\n\n将其格式化为Markdown风格的层次结构，同时也提供可以粘贴到思维导图工具中的格式。",
    promptTip:"思维导图最适合用于规划论文、复习考试和头脑风暴项目。在Miro或MindMeister上开始一个中心话题，然后请AI帮你扩展每个分支。",
    tools:["ChatGPT","Claude","Miro","MindMeister"],
    links:[{name:"Miro",url:"https://miro.com"},{name:"MindMeister",url:"https://www.mindmeister.com"}]},

  {id:17, title:"练习辩论和批判性思维", subtitle:"更聪明地论证", category:"learning",
    description:"AI是一个优秀的辩论练习伙伴。它可以为任何话题呈现多个角度，帮助你构建更强的论点并发现逻辑谬误。",
    steps:["选择一个辩论话题","请AI呈现正反两方","练习你的论点","请AI指出你推理中的弱点"],
    prompt:"我们来辩论：[话题]。\n\n首先，给我这个问题的背景，呈现双方最有力的论点。\n\n然后，我会采取[正方/反方]立场。请你论证相反的一方。\n\n规则：\n- 使用逻辑论证而非感情诉求\n- 引用数据或例子支撑你的观点\n- 指出我论点中的逻辑谬误\n- 辩论结束后，公正分析双方\n\n让它像正式的竞技辩论一样。",
    promptTip:"批判性思维是你能在学校学到的最重要的技能之一。请AI'找出我论证中的逻辑谬误'——并学会识别它们。",
    tools:["ChatGPT","Claude","Gemini","Perplexity"],
    links:[{name:"ChatGPT",url:"https://chat.openai.com"},{name:"Perplexity",url:"https://perplexity.ai"}]},

  {id:18, title:"理解历史事件", subtitle:"让历史栩栩如生", category:"learning",
    description:"AI可以让历史变得生动有趣——讲述不同视角的故事、创建时间线、模拟与历史人物的对话，以及展示事件之间的联系。",
    steps:["选择一个时期、事件或人物","请AI从多个角度呈现","探索'如果历史不一样'的假设场景","创建时间线和因果联系"],
    prompt:"帮我深入理解[历史事件/时期/人物]。\n\n请提供：\n1. 关键事件时间线\n2. 来自不同立场的多个视角\n3. 不太为人知但有趣的事实\n4. 这些事件的长远影响及如何影响了今天\n5. 与同时代其他事件的联系\n6. 模拟一个与[历史人物]的简短对话，谈论[话题]\n\n让它引人入胜——像在讲故事，而不是教科书。",
    promptTip:"历史充满了迷人的故事。请AI讲述'围绕[事件]最意想不到的故事'或'从[失败一方]的角度解释[事件]'以获得新视角。",
    tools:["ChatGPT","Claude","Perplexity"],
    links:[{name:"Perplexity",url:"https://perplexity.ai"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:19, title:"探索科学概念", subtitle:"将科学变为有趣的体验", category:"learning",
    description:"AI可以让科学变得有趣、可接触和可互动。从模拟实验到逐步解释复杂理论——就像拥有一个科学实验室和教授的组合。",
    steps:["选择你想探索的科学话题","请AI用简单的术语解释","请求互动思想实验","用练习题测试你的理解"],
    prompt:"帮我理解[科学概念/话题]。我的水平是[初中/高中/大学入门]。\n\n请：\n1. 从一个日常类比开始\n2. 逐步解释底层科学\n3. 包括一个我可以在家做的思想实验或简单实验\n4. 展示这在现实世界中如何应用\n5. 创建一个5题测验来检验我的理解\n6. 推荐一个相关的YouTube视频或资源\n\n让它引人入胜——我想因为好奇而学习，不是因为必须学习。",
    promptTip:"最好的科学学习方式是提问'为什么？'和'如果不是这样呢？'。请AI设计你可以在家做的实验来测试概念。理论+实践=理解。",
    tools:["ChatGPT","Claude","Wolfram Alpha","PhET"],
    links:[{name:"PhET Simulations",url:"https://phet.colorado.edu"},{name:"Wolfram Alpha",url:"https://www.wolframalpha.com"}]},

  {id:20, title:"掌握数学概念", subtitle:"AI让数学变得有意义", category:"learning",
    description:"无论你热爱数学还是苦于数学，AI都可以帮你理解概念、逐步解题，并通过练习建立自信。最棒的是——它可以用任何你理解的方式解释。",
    steps:["分享你在学习的数学话题","请AI逐步解释概念","练习类似的题目","请AI在不给答案的情况下给你提示"],
    prompt:"帮我理解[数学话题：代数/几何/微积分/统计/三角函数]。具体来说：[具体概念或题目]。\n\n请：\n1. 直观地解释概念（用图片、类比）\n2. 展示一道详细的解题过程\n3. 解释每一步的原因\n4. 给我3道类似的练习题\n5. 当我尝试解题时给提示而不是答案\n6. 展示这个数学在现实生活中的用处\n\n如果我困惑了，请用完全不同的方法尝试。",
    promptTip:"理解比记忆更重要。请AI解释'为什么这个公式有效'而不只是'如何使用这个公式'。使用Wolfram Alpha来验证你的答案和查看解题步骤。",
    tools:["ChatGPT","Claude","Wolfram Alpha","Desmos"],
    links:[{name:"Wolfram Alpha",url:"https://www.wolframalpha.com"},{name:"Desmos",url:"https://www.desmos.com"}]},

  {id:103, title:"学习如何提示", subtitle:"掌握与AI对话的艺术", category:"learning",
    description:"你提问的方式直接决定了AI回答的质量。学习提示工程——AI的语言——可以将普通的回复变成出色的结果。这是最有价值的AI技能。",
    steps:["理解AI的基本工作原理","学习关键提示技巧（角色设定、少样本、思维链）","通过提供更多上下文来练习改进你的提示","比较不同提示获得的不同结果"],
    prompt:"做我的提示工程导师。教我如何写出更好的AI提示。\n\n从以下内容开始：\n1. 弱提示和强提示并排对比的5个例子\n2. 需要学习的核心提示技巧\n3. 我可以立即开始使用的提示模板\n4. 测试我技能的练习\n\n然后给我3个挑战：给我一个目标，让我写出达到该目标的最佳提示。",
    promptTip:"CRAFT方法：上下文（Context）、角色（Role）、行动（Action）、格式（Format）、语气（Tone）。你的提示越具体越好。尝试用不同的提示提同一个问题——你会对结果差异感到惊讶。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"ChatGPT",url:"https://chat.openai.com"},{name:"Claude",url:"https://claude.ai"}]},

  // ===== 艺术与设计 (21-30) =====
  {id:21, title:"生成数字艺术", subtitle:"用文字描述创作惊艳视觉作品", category:"art",
    description:"AI图像生成器可以根据你的文字描述创作令人惊叹的艺术作品。从逼真的照片到抽象画，用你的想象力引导AI——不需要画画技能。",
    steps:["描述你想创作的图像","选择风格（逼真的/动漫/油画/数字艺术）","使用AI图像生成器创建","通过调整提示来迭代优化"],
    prompt:"创建一幅[描述场景/主题]的图像。\n\n风格：[摄影级逼真/数字艺术/水彩画/动漫/油画/极简主义]\n色调：[温暖/冷色/鲜艳/柔和/暗调]\n构图：[特写/广角/鸟瞰/肖像]\n光线：[自然光/金色时刻/霓虹/戏剧性/柔和]\n\n关键元素要包括：[列出重要细节]\n需要避免的：[不想看到的元素]",
    promptTip:"提示越具体，效果越好。提及艺术风格、光线、色彩和构图。尝试添加'以[艺术家]风格'获得特定美学。在Midjourney中使用--ar来改变宽高比。",
    tools:["Midjourney","DALL-E","Stable Diffusion","Leonardo AI"],
    links:[{name:"Midjourney",url:"https://www.midjourney.com"},{name:"Leonardo AI",url:"https://leonardo.ai"}]},

  {id:22, title:"设计Logo和品牌形象", subtitle:"创建专业的品牌视觉", category:"art",
    description:"AI可以帮你设计logo概念、选择品牌颜色、创建视觉识别系统。非常适合学校项目、个人品牌和创业想法。",
    steps:["描述你的品牌/项目以及它代表什么","请AI生成logo概念和配色方案","用Canva等工具优化","创建一致的品牌指南"],
    prompt:"为[品牌/项目名称]设计一个logo概念。它是关于[描述]的。\n\n品牌个性：[现代/复古/有趣/专业/极简/大胆]\n目标受众：[描述]\n偏好颜色：[有偏好的话]\n风格偏好：[文字标志/图标/组合/吉祥物]\n\n请提供：\n1. 3个不同的logo概念描述\n2. 每个的配色方案（含十六进制代码）\n3. 字体建议\n4. 这些设计在名片和社交媒体上的效果说明",
    promptTip:"简约logo效果最好。在各种尺寸下都应该好看——从名片到广告牌。使用Canva或Figma根据AI的建议创建实际设计。",
    tools:["Midjourney","DALL-E","Canva","Figma"],
    links:[{name:"Canva",url:"https://www.canva.com"},{name:"Figma",url:"https://www.figma.com"}]},

  {id:23, title:"创建漫画和插图", subtitle:"让你的故事可视化", category:"art",
    description:"AI可以帮你创作漫画——从角色设计到面板布局再到完整的视觉叙事。把你的故事变成视觉杰作。",
    steps:["开发你的角色和故事","用AI生成角色设计和场景","用AI辅助创建漫画面板布局","在Canva或专业工具中组装完整的漫画"],
    prompt:"帮我为一个关于[故事概念]的漫画/插图创建视觉效果。\n\n角色：\n1. [姓名]：[外观描述、个性]\n2. [姓名]：[外观描述、个性]\n\n场景：[描述发生了什么]\n风格：[日本漫画/美式漫画/网络漫画/卡通]\n色调：[有趣的/戏剧性的/动作/温馨的]\n\n请描述这些面板的视觉效果，然后我将使用AI图像工具来生成它们。",
    promptTip:"在生成图像之前保持角色描述一致。创建一个'角色设计稿'——带有详细描述的参考图像——然后在每个面板中引用它。",
    tools:["Midjourney","DALL-E","Canva","Clip Studio Paint"],
    links:[{name:"Canva",url:"https://www.canva.com"},{name:"Clip Studio Paint",url:"https://www.clipstudio.net"}]},

  {id:24, title:"编辑和增强照片", subtitle:"AI驱动的照片编辑", category:"art",
    description:"AI照片编辑工具可以去除背景、增强颜色、修复旧照片，甚至改变照片中的元素。结果专业，无需专业技能。",
    steps:["选择你想编辑的照片","选择合适的AI编辑工具","描述你想要的修改","微调结果"],
    prompt:"我需要对我的照片进行以下编辑：\n\n当前照片描述：[描述照片中有什么]\n我想要的更改：\n1. [更改1：例如，去除背景]\n2. [更改2：例如，增强光线]\n3. [更改3：例如，调整颜色]\n\n最终目的：[用于什么——社交媒体头像/作品集/打印]\n风格偏好：[自然/戏剧性/复古/高对比度]\n\n请推荐最佳工具并提供逐步说明。",
    promptTip:"对于快速背景去除，试试remove.bg。对于更高级的AI编辑，Photoshop的生成填充或Canva的魔法编辑非常强大。始终保存原图！",
    tools:["Adobe Photoshop","Canva","Remove.bg","Lightroom"],
    links:[{name:"Remove.bg",url:"https://www.remove.bg"},{name:"Canva",url:"https://www.canva.com"}]},

  {id:25, title:"创建动画和动态图形", subtitle:"让你的设计动起来", category:"art",
    description:"AI可以帮你创建引人注目的动画——从简单的GIF到复杂的动态图形。非常适合社交媒体、演示文稿和创意项目。",
    steps:["描述你想要的动画","选择合适的工具和风格","用AI辅助创建关键帧","导出并分享你的动画"],
    prompt:"帮我创建一个[类型：短视频开场/社交媒体动态帖/解释动画/logo动画]。\n\n描述：[什么应该在画面上发生]\n时长：[秒数]\n风格：[2D/3D/定格动画/动态文字]\n色调：[有趣/专业/酷炫/优雅]\n\n请提供：\n1. 逐帧的故事板描述\n2. 动画技巧建议\n3. 推荐工具和教程\n4. 如果可能的话，用CSS/JS动画的代码",
    promptTip:"从简单开始——一个好的动态文字动画可以非常有效。Canva有内置动画功能，LottieFiles有免费的动画可以使用。",
    tools:["Canva","LottieFiles","Adobe After Effects","Rive"],
    links:[{name:"Canva",url:"https://www.canva.com"},{name:"LottieFiles",url:"https://lottiefiles.com"}]},

  {id:26, title:"设计T恤和商品", subtitle:"创建可穿戴的艺术", category:"art",
    description:"AI让每个人都能成为商品设计师。创建T恤、贴纸、手机壳等的独特设计。用按需打印服务销售，无需库存。",
    steps:["构思你的设计概念","使用AI图像工具生成设计","优化分辨率和格式以适合打印","上传到按需打印平台"],
    prompt:"为[产品类型：T恤/连帽衫/贴纸/手机壳/帆布包]创建一个设计。\n\n概念：[描述你想要的]\n风格：[极简线条画/复古/涂鸦/波普艺术/打字排版/可爱卡通]\n颜色：[单色/全彩/有限调色板]\n目标受众：[谁会购买/穿戴]\n文字（如果有的话）：[想包含的文字或短语]\n\n确保设计在[深色/浅色]背景上效果好。\n提供打印文件规格（分辨率、尺寸、文件格式）。",
    promptTip:"T恤设计应该简洁大胆。文字要大号可读。使用AI生成概念，然后在Canva中清理。按需打印（如Redbubble、Teespring）零风险——有人买才会打印。",
    tools:["Midjourney","DALL-E","Canva","Redbubble"],
    links:[{name:"Redbubble",url:"https://www.redbubble.com"},{name:"Canva",url:"https://www.canva.com"}]},

  {id:27, title:"生成配色方案", subtitle:"为你的项目找到完美色彩", category:"art",
    description:"色彩选择可以成就或毁灭一个设计。AI可以根据情绪、主题或灵感生成和谐的配色方案——配有色彩心理学解释。",
    steps:["描述你项目的情绪和目的","请AI生成配色方案","了解每种颜色选择背后的原因","在你的设计中应用这些方案"],
    prompt:"为[项目类型：网站/品牌/房间设计/活动/艺术项目]生成一个配色方案。\n\n情绪/氛围：[宁静/充满活力/专业/有趣/奢华]\n灵感：[任何参考——自然、城市、时代等]\n\n请提供：\n1. 主色（含十六进制代码和RGB值）\n2. 4-5个辅助色\n3. 每种颜色选择的心理学解释\n4. 浅色和深色模式变体\n5. 关于在何处使用每种颜色的建议\n6. 无障碍注意事项",
    promptTip:"使用Coolors.co实时预览你的配色方案。坚持60-30-10法则：60%主色，30%辅色，10%强调色。测试色盲无障碍性！",
    tools:["ChatGPT","Claude","Coolors","Adobe Color"],
    links:[{name:"Coolors",url:"https://coolors.co"},{name:"Adobe Color",url:"https://color.adobe.com"}]},

  {id:28, title:"创建图案和纹理", subtitle:"为各种项目设计无缝图案", category:"art",
    description:"AI可以生成可用于织物、壁纸、网页背景等的无缝图案和纹理。从简单的几何图案到复杂的有机设计。",
    steps:["描述你想要的图案类型","指定用途和重复要求","用AI生成图案设计","在你的项目中应用"],
    prompt:"创建一个[类型：几何/花卉/抽象/有机/民族/极简]的无缝图案设计。\n\n用途：[织物/壁纸/网页背景/包装纸/品牌]\n色彩方案：[描述你想要的颜色]\n密度：[密集/中等/稀疏]\n复杂度：[简单/中等/复杂]\n\n提供多种变体和比例建议。",
    promptTip:"无缝图案需要边缘完美对齐。在Photoshop或Canva中测试图案的平铺效果。简单图案往往更通用——从基础开始再增加复杂度。",
    tools:["Midjourney","DALL-E","Adobe Illustrator","Canva"],
    links:[{name:"Canva",url:"https://www.canva.com"},{name:"Coolors",url:"https://coolors.co"}]},

  {id:29, title:"设计社交媒体图片", subtitle:"制作引人注目的帖子", category:"art",
    description:"AI帮你为每个平台创建完美尺寸、引人注目的社交媒体图片。从Instagram故事到YouTube缩略图——每个帖子都脱颖而出。",
    steps:["选择平台和内容类型","用AI生成设计概念","在Canva中创建","按格式和时间表发布"],
    prompt:"为[平台：Instagram帖子/故事/YouTube缩略图/Twitter横幅/LinkedIn]设计一张图片。\n\n内容：[图片主题]\n品牌颜色：[你的颜色，或请AI建议]\n文字（如果有的话）：[任何覆盖文字]\n风格：[极简/大胆/优雅/有趣/专业]\n\n提供：\n1. 设计概念描述\n2. 精确尺寸（像素）\n3. 布局建议\n4. 字体搭配推荐\n5. 如何在Canva中创建的步骤",
    promptTip:"每个平台有不同的最佳图片尺寸。Instagram：1080x1080。故事：1080x1920。YouTube缩略图：1280x720。始终先检查。",
    tools:["Canva","Midjourney","Adobe Express","Figma"],
    links:[{name:"Canva",url:"https://www.canva.com"},{name:"Adobe Express",url:"https://www.adobe.com/express"}]},

  {id:30, title:"修复和着色旧照片", subtitle:"给回忆带来新生命", category:"art",
    description:"AI可以修复受损的旧照片——修复裂缝、去除划痕，甚至为黑白照片着色。给你的家庭历史带来新生命。",
    steps:["扫描或拍摄旧照片","上传到AI修复工具","选择修复选项（修复、着色、增强）","保存和分享修复后的版本"],
    prompt:"我有一张旧照片需要修复。照片状况：[描述损坏——裂缝/褪色/划痕/发黄/缺失部分]。照片类型：[黑白/彩色/棕褐色]。\n\n我想要：\n1. 修复损坏区域\n2. 增强清晰度和细节\n3. [如果黑白]着色使其自然\n4. 调整亮度和对比度\n\n请推荐最佳工具并提供逐步说明。同时解释我对结果应有的期望。",
    promptTip:"更高分辨率的扫描件效果更好。以600DPI或更高进行扫描。AI着色可能不完全准确——参考同时期的彩色照片进行调整。始终保存原始文件。",
    tools:["Remini","MyHeritage","Adobe Photoshop","DALL-E"],
    links:[{name:"Remini",url:"https://remini.ai"},{name:"MyHeritage",url:"https://www.myheritage.com/photo-enhancer"}]},

  // ===== 音乐与音频 (31-40) =====
  {id:31, title:"创作原创音乐", subtitle:"不会乐器也能作曲", category:"music",
    description:"AI音乐工具让任何人都能创作原创音乐。描述你想要的心情和风格，AI就能生成完整的曲目。从lo-fi节拍到交响乐，可能性无限。",
    steps:["描述你想要的音乐（情绪、风格、节奏）","使用AI音乐工具生成曲目","试听并给出反馈来优化","下载并在你的项目中使用"],
    prompt:"创作一首[类型：lo-fi hip-hop/流行/电子/古典/摇滚/环境音乐]曲目。\n\n情绪：[放松/充满活力/忧郁/史诗/欢快]\n节奏：[慢/中/快] BPM\n乐器：[钢琴/吉他/合成器/弦乐/鼓/混合]\n时长：[秒/分钟]\n用途：[YouTube视频/播客/学习/游戏/社交媒体]\n\n灵感参考：[听起来像什么歌曲或艺术家]",
    promptTip:"从心情开始，而不是技术细节。'听起来像深夜独自开车'比'E小调4/4拍120BPM'对AI更有效。一次一次迭代——先确定节拍，然后添加层次。",
    tools:["Suno","Udio","AIVA","Soundraw"],
    links:[{name:"Suno",url:"https://suno.ai"},{name:"Udio",url:"https://www.udio.com"}]},

  {id:32, title:"创作歌词", subtitle:"AI辅助词曲创作", category:"music",
    description:"AI可以帮你写歌词——从头脑风暴主题到创建完整的歌词。它理解韵律方案、节奏模式和歌曲结构，同时保持你的创意愿景。",
    steps:["分享你的歌曲主题和情感","选择风格和结构","与AI一起写和修改歌词","将歌词与音乐匹配"],
    prompt:"帮我写一首关于[主题/情感/故事]的歌词。\n\n风格：[流行/说唱/民谣/摇滚/R&B/乡村]\n情绪：[快乐/心碎/励志/派对/沉思]\n结构：[主歌-副歌-主歌-副歌-桥段-副歌]\n\n请提供：\n1. 3个有力的歌曲标题选项\n2. 完整的歌词（含主歌、副歌和桥段标注）\n3. 押韵方案和音节模式\n4. 副歌要朗朗上口\n5. 为不同情绪的替代版本",
    promptTip:"最好的歌词结合个人经历和普遍情感。分享一段真实记忆或感受作为起点——AI可以帮你把它变成一首歌。",
    tools:["ChatGPT","Claude","Suno","Udio"],
    links:[{name:"Suno",url:"https://suno.ai"},{name:"RhymeZone",url:"https://www.rhymezone.com"}]},

  {id:33, title:"生成音效和音景", subtitle:"为任何项目定制音频", category:"music",
    description:"AI可以创建自定义音效、环境音景和音频元素。非常适合视频、播客、游戏和演示文稿。",
    steps:["描述你需要的音效","选择合适的AI音频工具","生成并预览音效","下载并整合到你的项目中"],
    prompt:"为[项目类型：视频/播客/游戏/演示文稿]创建以下音效：\n\n1. [音效1描述]\n2. [音效2描述]\n3. [音效3描述]\n\n还要创建一个[类型：森林/城市/海洋/太空/咖啡馆]的背景音景，时长[分钟]。\n\n所有音频应该：\n- 高质量（至少16位44.1kHz）\n- 没有版权问题\n- 适合[商业/个人]使用",
    promptTip:"将音景分层创造更丰富的声音。从基础环境开始，然后添加特定的声音元素。免费音效也可以在Freesound.org找到。",
    tools:["ElevenLabs","Stable Audio","Freesound","Epidemic Sound"],
    links:[{name:"ElevenLabs",url:"https://elevenlabs.io"},{name:"Freesound",url:"https://freesound.org"}]},

  {id:34, title:"混音和制作音乐", subtitle:"AI驱动的音乐制作", category:"music",
    description:"AI让音乐制作变得更加容易。从自动混音到母带处理，AI工具可以帮你获得专业级的声音，无需数年的训练。",
    steps:["录制或选择你的音频素材","使用AI工具进行混音和增强","调整设置获得完美声音","导出发行级质量的曲目"],
    prompt:"帮我混音和制作一首[类型]曲目。我有以下音轨：\n[列出你的音轨：人声、吉他、鼓等]\n\n我想要的声音效果：[描述参考——像什么歌曲/艺术家]\n\n请提供：\n1. 建议的混音设置（EQ、压缩、混响）\n2. 每个音轨的处理建议\n3. 母带处理指南\n4. 推荐的免费/便宜工具\n5. 常见的新手混音错误以及如何避免",
    promptTip:"好的混音从好的录音开始。在安静的环境中录制，使用质量好的麦克风。BandLab是免费且对初学者友好的DAW。LANDR可以AI自动母带处理。",
    tools:["BandLab","LANDR","iZotope","GarageBand"],
    links:[{name:"BandLab",url:"https://www.bandlab.com"},{name:"LANDR",url:"https://www.landr.com"}]},

  {id:35, title:"创建播客", subtitle:"用AI启动你的播客", category:"music",
    description:"AI帮助播客的每个阶段——从规划剧集和撰写脚本到编辑音频和生成节目笔记。用更少的努力启动你的播客。",
    steps:["定义你的播客概念和目标受众","用AI规划剧集和编写大纲","录制你的剧集","用AI编辑音频并创建节目笔记"],
    prompt:"帮我为一个关于[话题]的播客规划[数量]集。目标听众：[受众描述]。\n\n请提供：\n1. 吸引人的播客名称（5个选项）\n2. 播客描述/简介\n3. 前[数量]集的大纲，每集包含：\n   - 剧集标题\n   - 关键话题和讨论要点\n   - 建议的嘉宾类型\n   - 每集时长建议\n4. 介绍脚本\n5. 技术设置建议（设备、软件）\n6. 发布和推广策略",
    promptTip:"一致性比完美更重要。先用手机录几集，再投资设备。用AI编辑工具如Descript来轻松编辑——它可以像编辑文本一样编辑音频。",
    tools:["ChatGPT","Claude","Descript","Anchor"],
    links:[{name:"Descript",url:"https://www.descript.com"},{name:"Anchor",url:"https://anchor.fm"}]},

  {id:36, title:"生成AI语音和旁白", subtitle:"任何内容的专业级语音", category:"music",
    description:"AI可以生成各种语言、口音和风格的逼真语音。非常适合旁白、有声书、视频解说和无障碍内容。",
    steps:["编写你的脚本","选择语音风格和语言","用AI语音工具生成","微调节奏和情感"],
    prompt:"为[内容类型：YouTube视频/演示文稿/有声书/广告/教程]生成旁白。\n\n脚本：[你的文字]\n\n语音要求：\n- 性别：[男/女/中性]\n- 年龄感觉：[年轻/中年/成熟]\n- 语气：[专业/友好/兴奋/平静/权威]\n- 语言：[语言]\n- 节奏：[慢/正常/快]\n\n添加适当的停顿和强调。",
    promptTip:"好的旁白是关于节奏而非速度的。使用ElevenLabs获得最逼真的语音。始终标注AI生成的语音——透明度很重要。",
    tools:["ElevenLabs","Play.ht","Murf","Amazon Polly"],
    links:[{name:"ElevenLabs",url:"https://elevenlabs.io"},{name:"Play.ht",url:"https://play.ht"}]},

  {id:37, title:"创作节拍和伴奏", subtitle:"为你的表演制作伴奏", category:"music",
    description:"需要rap的节拍？练习的伴奏？视频的背景音乐？AI可以生成任何风格和节奏的自定义节拍和伴奏。",
    steps:["描述你需要的节拍类型","指定BPM、调式和风格","使用AI工具生成","下载并在你的项目中使用"],
    prompt:"创建一个[风格：trap/boom-bap/lo-fi/pop/R&B/电子]节拍。\n\n规格：\n- BPM：[节奏]\n- 调式：[如果有偏好]\n- 时长：[分钟]\n- 乐器：[808低音/合成器/采样/原声]\n- 氛围：[黑暗/欢快/梦幻/硬核/感性]\n\n参考：[听起来像什么歌曲或制作人]\n\n请同时提供歌曲结构建议（前奏、主歌、副歌等部分）。",
    promptTip:"先确定BPM和氛围——这是节拍的基础。使用Suno或Udio快速生成完整曲目。BandLab可以免费分层编辑节拍。",
    tools:["Suno","BandLab","Splice","Udio"],
    links:[{name:"Suno",url:"https://suno.ai"},{name:"BandLab",url:"https://www.bandlab.com"}]},

  {id:38, title:"转录和字幕", subtitle:"把音频变成文字", category:"music",
    description:"AI可以快速准确地将音频和视频转录成文字。非常适合课堂笔记、会议记录、字幕和无障碍功能。",
    steps:["上传你的音频或视频文件","让AI转录内容","审阅并编辑准确性","导出为你需要的格式"],
    prompt:"转录这段[音频/视频]并：\n1. 准确识别不同说话者\n2. 添加时间戳（每[30秒/1分钟]）\n3. 标注[嗯]、[笑]等非语言元素\n4. 格式化为可读的段落\n5. 创建关键要点摘要\n6. 生成适当格式的字幕文件（SRT格式）\n\n语言：[语言]\n说话者数量：[数量]\n主题：[话题，帮助提高准确性]",
    promptTip:"Whisper（OpenAI的免费工具）非常准确。对于视频字幕，YouTube有内置的自动字幕功能。始终手动检查专业术语和人名。",
    tools:["Whisper","Descript","Otter.ai","Rev"],
    links:[{name:"Otter.ai",url:"https://otter.ai"},{name:"Descript",url:"https://www.descript.com"}]},

  {id:39, title:"分析和学习音乐", subtitle:"用AI理解音乐理论", category:"music",
    description:"AI可以分析歌曲——从和弦进行到歌曲结构。学习你喜欢的音乐是如何制作的，并将这些知识应用到你自己的创作中。",
    steps:["分享你想分析的歌曲","请AI分解音乐元素","学习使用的理论概念","将所学应用到你自己的音乐中"],
    prompt:"分析这首歌曲：[歌曲名称] by [艺术家]。\n\n请分析：\n1. 和弦进行和调式\n2. 歌曲结构（主歌/副歌/桥段等）\n3. 节奏模式和BPM\n4. 旋律特点\n5. 制作技巧（可以听到的效果和处理）\n6. 什么让这首歌情感上有效\n7. 背后的音乐理论\n\n然后建议3首类似的歌曲供我学习，并解释它们的共同点。",
    promptTip:"从你喜欢的歌曲开始学习理论——比课本有趣得多。请AI'教我怎么在吉他/钢琴上弹这首歌的简化版本'。",
    tools:["ChatGPT","Claude","Chordify","Spotify"],
    links:[{name:"Chordify",url:"https://chordify.net"},{name:"Spotify",url:"https://www.spotify.com"}]},

  {id:40, title:"AI DJ和播放列表", subtitle:"完美的音乐混搭", category:"music",
    description:"AI可以根据你的心情、活动或偏好创建完美的播放列表和混音。就像拥有一个了解你所有音乐品味的私人DJ。",
    steps:["描述你的心情、活动或偏好","让AI推荐歌曲和创建列表","在音乐平台上收听","给出反馈获得更好的推荐"],
    prompt:"为[场合：学习/健身/派对/放松/公路旅行/约会之夜]创建一个[数量]首歌的播放列表。\n\n我的音乐品味：[描述你喜欢的类型和艺术家]\n氛围：[能量水平从1-10]\n发现新歌曲：[是的，混入我可能不知道的曲目 / 不，只要经典]\n\n请提供：\n1. 按播放顺序排列的歌曲列表\n2. 为什么每首歌适合这个场合\n3. 播放列表中的流畅过渡\n4. 替代选择以备不时之需\n5. 一个Spotify搜索链接（如果可能）",
    promptTip:"尝试'给我推荐像[歌曲名]这样的歌，但更[形容词]'来发现新音乐。Spotify的AI DJ功能也很出色。创建不同心情的播放列表库。",
    tools:["Spotify","ChatGPT","Apple Music","YouTube Music"],
    links:[{name:"Spotify",url:"https://www.spotify.com"},{name:"Apple Music",url:"https://music.apple.com"}]},

  // ===== 视频与动画 (41-50) =====
  {id:41, title:"创建短视频内容", subtitle:"制作TikTok和Reels级别的视频", category:"video",
    description:"AI帮你规划、编写脚本和编辑适合TikTok、Instagram Reels和YouTube Shorts的短视频。从创意构思到最终发布——AI加速每个步骤。",
    steps:["定义你的视频概念和平台","用AI编写脚本和规划拍摄","录制你的内容","用AI辅助编辑和添加效果"],
    prompt:"帮我创建一个[平台：TikTok/Reels/YouTube Shorts]的短视频。\n\n话题：[话题]\n风格：[教育性/搞笑/故事/展示/趋势]\n时长：[15/30/60]秒\n目标受众：[受众描述]\n\n请提供：\n1. 3个创意概念\n2. 选定概念的逐秒脚本\n3. 拍摄角度和过渡建议\n4. 文字覆盖和字幕\n5. 音乐/音效推荐\n6. 最佳发布时间和标签策略",
    promptTip:"前3秒决定生死。用引人注目的开场钩子。保持剪辑快速——不要让任何镜头超过3秒。加字幕——85%的人静音观看。",
    tools:["ChatGPT","CapCut","Canva","InShot"],
    links:[{name:"CapCut",url:"https://www.capcut.com"},{name:"Canva视频",url:"https://www.canva.com/video-editor"}]},

  {id:42, title:"制作解说视频", subtitle:"视觉化解释任何概念", category:"video",
    description:"解说视频是传达复杂想法最有效的方式之一。AI帮你编写脚本、创建故事板和制作引人注目的解说动画。",
    steps:["定义你要解释的概念","用AI编写清晰的脚本","创建故事板和视觉规划","用动画工具制作"],
    prompt:"为[概念/产品/服务]创建一个[时长]分钟的解说视频脚本和故事板。\n\n受众：[谁需要理解这个]\n复杂程度：[简单概述/详细说明]\n风格：[动画/真人/屏幕录制/混合]\n语气：[有趣/专业/友好/严肃]\n\n请提供：\n1. 完整的旁白脚本\n2. 逐场景故事板描述\n3. 每个场景的视觉建议\n4. 时间线和节奏指南\n5. 背景音乐风格建议",
    promptTip:"保持简单：一个视频解释一个概念。用'问题-解决方案-好处'的结构。前10秒要说明为什么观众应该继续看。",
    tools:["ChatGPT","Canva","Vyond","Powtoon"],
    links:[{name:"Canva",url:"https://www.canva.com"},{name:"Vyond",url:"https://www.vyond.com"}]},

  {id:43, title:"从文字生成视频", subtitle:"AI将你的文字变成视频", category:"video",
    description:"AI视频生成器可以将文本描述转化为实际视频片段。从产品展示到概念可视化，不需要相机或视频编辑技能。",
    steps:["编写详细的视频描述","选择AI视频生成工具","生成并预览视频","编辑和优化结果"],
    prompt:"根据以下描述生成一个视频片段：\n\n场景：[详细描述你想看到的]\n时长：[秒]\n风格：[逼真/动画/电影级/梦幻]\n摄像机移动：[固定/缓慢推进/环绕/跟踪]\n光线：[自然/戏剧性/柔和/霓虹]\n色调：[温暖/冷色/鲜艳/复古]\n\n这个视频将用于[用途]。",
    promptTip:"AI视频生成仍在快速发展中。对于最佳效果，给出非常详细的描述。Runway是目前最好的文字转视频工具之一。短片段效果比长视频好。",
    tools:["Runway","Pika","Kling","Sora"],
    links:[{name:"Runway",url:"https://runwayml.com"},{name:"Pika",url:"https://pika.art"}]},

  {id:44, title:"编辑视频", subtitle:"AI驱动的视频编辑", category:"video",
    description:"AI让视频编辑变得更快更容易。从自动剪辑到智能字幕生成，AI工具让每个人都能制作专业级视频。",
    steps:["导入你的原始素材","使用AI工具进行自动编辑","微调剪辑、过渡和效果","导出最终版本"],
    prompt:"帮我为[项目类型：YouTube视频/vlog/演示/社交媒体/学校项目]编辑视频。\n\n原始素材：[描述你有什么素材]\n目标时长：[分钟]\n风格：[快节奏/电影级/简洁/有趣]\n\n我需要帮助：\n1. 选择最佳片段的策略\n2. 过渡和节奏建议\n3. 文字和图形叠加\n4. 颜色校正指导\n5. 音乐和音效搭配\n6. 适合我水平的推荐编辑工具",
    promptTip:"CapCut是免费的，有出色的AI功能。对于更专业的编辑，DaVinci Resolve是免费的，功能媲美付费软件。先学会讲好故事再追求花哨效果。",
    tools:["CapCut","DaVinci Resolve","Adobe Premiere","Descript"],
    links:[{name:"CapCut",url:"https://www.capcut.com"},{name:"DaVinci Resolve",url:"https://www.blackmagicdesign.com/products/davinciresolve"}]},

  {id:45, title:"创建动画视频", subtitle:"让你的创意动起来", category:"video",
    description:"AI可以帮助创建各种动画——从简单的动态图形到角色动画。不需要动画经验，AI让过程变得简单。",
    steps:["定义你的动画概念","选择动画风格和工具","用AI辅助创建","渲染并导出"],
    prompt:"帮我创建一个[类型：2D角色动画/动态文字/信息图动画/产品展示/logo动画]。\n\n概念：[描述动画应该展示什么]\n风格：[卡通/极简/3D/手绘/企业]\n时长：[秒]\n色彩方案：[描述]\n\n请提供：\n1. 详细的故事板（逐帧）\n2. 动画技巧建议\n3. 推荐工具\n4. 如何在Canva或其他免费工具中实现\n5. 导出设置建议",
    promptTip:"简单的动画往往最有效。动态文字（文字动画）和简单的图标动画制作快，效果好。Canva的动画功能适合初学者。",
    tools:["Canva","Runway","Adobe After Effects","Rive"],
    links:[{name:"Canva",url:"https://www.canva.com"},{name:"Runway",url:"https://runwayml.com"}]},

  {id:46, title:"制作屏幕录制教程", subtitle:"分享你的知识", category:"video",
    description:"屏幕录制教程是分享知识最有效的方式之一。AI帮你规划内容、编写脚本和编辑——让你的教程既专业又有教育性。",
    steps:["规划你的教程内容和结构","编写清晰的脚本","录制屏幕和旁白","用AI辅助编辑和增强"],
    prompt:"帮我创建一个关于[话题：如何使用[软件]/如何[技能]/如何[过程]]的屏幕录制教程。\n\n受众：[初学者/中级/高级]\n时长：[分钟]\n\n请提供：\n1. 教程大纲和各部分时间分配\n2. 逐步脚本（旁白要说的话）\n3. 每一步的屏幕上应该展示什么\n4. 关键提示和常见错误的注释\n5. 引人注目的标题和缩略图概念\n6. 推荐的录屏工具",
    promptTip:"保持教程专注——一个视频解决一个问题。使用缩放和高亮来引导观众注意力。OBS是免费的专业录屏工具。记得在重要步骤加字幕。",
    tools:["OBS Studio","Loom","Descript","CapCut"],
    links:[{name:"OBS Studio",url:"https://obsproject.com"},{name:"Loom",url:"https://www.loom.com"}]},

  {id:47, title:"创建视频缩略图", subtitle:"让人一定要点击", category:"video",
    description:"缩略图是决定人们是否观看你视频的关键。AI帮你创建引人注目、点击率高的缩略图，让你的视频脱颖而出。",
    steps:["分析成功的缩略图模式","用AI生成概念和设计","在Canva中创建","A/B测试不同版本"],
    prompt:"为一个标题为'[视频标题]'的YouTube视频创建缩略图概念。\n\n视频内容：[简要描述]\n频道风格：[描述你的品牌/风格]\n\n请提供：\n1. 3个不同的缩略图概念\n2. 每个概念的关键视觉元素\n3. 文字叠加建议（3-5个词）\n4. 色彩方案建议\n5. 表情/人脸建议（如果适用）\n6. 在Canva中创建的步骤\n\n让它在小尺寸下也能引人注目。",
    promptTip:"缩略图的黄金法则：大面孔+大文字+对比色。保持3个词以下的文字。在手机小屏上测试——如果看不清就太复杂了。",
    tools:["Canva","Midjourney","Adobe Express","Photoshop"],
    links:[{name:"Canva",url:"https://www.canva.com"},{name:"Adobe Express",url:"https://www.adobe.com/express"}]},

  {id:48, title:"生成视频字幕和翻译", subtitle:"让视频触达全球观众", category:"video",
    description:"AI可以自动生成准确的字幕和多语言翻译。让你的视频内容对全世界和听力障碍者都无障碍。",
    steps:["上传你的视频或音频","用AI生成字幕","审阅和编辑准确性","添加到视频或导出SRT文件"],
    prompt:"为我的[语言]视频生成字幕并翻译成[目标语言列表]。\n\n视频内容：[简要描述话题]\n说话者数量：[数量]\n\n要求：\n1. 准确的时间同步\n2. 正确的标点和大写\n3. 标注说话者身份（如果多人）\n4. 适当的断行（每行不超过[数字]个字符）\n5. 翻译要自然，不是逐字翻译\n6. 输出SRT格式\n\n同时标记任何可能需要人工校对的部分。",
    promptTip:"自动字幕准确率约95%，所以始终手动检查。对于翻译，让母语人士审阅关键术语。YouTube有免费的自动字幕功能。",
    tools:["Whisper","Descript","YouTube","CapCut"],
    links:[{name:"Descript",url:"https://www.descript.com"},{name:"CapCut",url:"https://www.capcut.com"}]},

  {id:49, title:"创建视频简介和结尾", subtitle:"专业的视频开场和结束", category:"video",
    description:"专业的简介和结尾让你的视频看起来更加精炼。AI帮你设计、编写脚本和创建令人印象深刻的视频开场和结束画面。",
    steps:["定义你的品牌风格","用AI设计简介和结尾概念","用Canva或视频工具创建","在你的视频中一致使用"],
    prompt:"为我的[类型：YouTube频道/品牌/系列]创建视频简介和结尾。\n\n品牌名称：[名称]\n风格：[专业/有趣/极简/充满活力]\n简介时长：5-10秒\n结尾时长：15-20秒\n\n简介应该包含：\n1. logo动画概念\n2. 频道名称和标语\n3. 背景音乐风格\n\n结尾应该包含：\n1. 订阅号召\n2. 下一个/推荐视频位置\n3. 社交媒体链接位置\n4. 匹配的背景音乐\n\n在Canva中如何创建的步骤说明。",
    promptTip:"简介要短——5秒以下最佳。如果简介太长观众会跳过。结尾要包含明确的行动号召。使用一致的品牌元素建立识别度。",
    tools:["Canva","CapCut","Panzoid","InVideo"],
    links:[{name:"Canva",url:"https://www.canva.com"},{name:"Panzoid",url:"https://panzoid.com"}]},

  {id:50, title:"规划和管理视频项目", subtitle:"从概念到发布", category:"video",
    description:"成功的视频需要好的规划。AI帮你管理整个视频制作流程——从创意开发到发布计划。",
    steps:["定义你的视频目标和受众","用AI创建制作计划","执行每个阶段","发布并分析表现"],
    prompt:"帮我规划一个[类型：YouTube系列/教程课程/纪录短片/品牌视频/活动宣传]的视频项目。\n\n概述：[简要描述项目]\n预算：[低/中/高或具体金额]\n时间线：[截止日期]\n团队：[独自/小团队/有什么资源]\n\n请提供：\n1. 预制作清单\n2. 拍摄日计划\n3. 后期制作工作流程\n4. 设备和软件建议\n5. 发布策略和时间表\n6. 关键指标追踪计划\n7. 每个阶段的里程碑时间线",
    promptTip:"预制作阶段投入的时间越多，制作阶段就越顺利。创建一个内容日历并坚持执行。批量制作（一天拍多个视频）效率更高。",
    tools:["ChatGPT","Claude","Notion","Trello"],
    links:[{name:"Notion",url:"https://www.notion.so"},{name:"Trello",url:"https://trello.com"}]},

  {id:101, title:"查看我们的AI媒体作品集", subtitle:"探索用AI创建的媒体项目展示", category:"video",
    description:"探索我们精选的AI生成媒体项目集——包括音乐、视频、动画等。看看AI工具创造性使用的真实案例，并获得你自己项目的灵感。",
    steps:["浏览作品集中不同类型的媒体","注意使用了哪些AI工具","学习每个项目背后的方法","将所学应用到你自己的创意项目中"],
    prompt:"我想了解使用AI进行创意媒体项目的最新能力。能给我展示不同AI媒体创作的例子吗——包括音乐、视频、图像和动画？对于每个例子，解释使用了什么工具以及一个人如何实现类似的效果。",
    promptTip:"记住查看使用的工具和采用的方法——理解'如何做'和实际作品一样有价值。尝试用类似技巧重新创作你喜欢的项目。",
    tools:["Suno","Runway","Midjourney","ElevenLabs"],
    links:[{name:"查看我们的AI媒体作品集",url:"showcase.html"}]},

  {id:102, title:"掌握AI视频创作", subtitle:"生成、编辑和增强任何类型的视频内容", category:"video",
    description:"AI视频工具已经非常强大——能让你生成整个场景、替换背景、添加特效和自动编辑内容。无论你是制作YouTube视频、社交媒体内容还是创意项目，AI都能帮你实现之前需要大型工作室才能完成的效果。",
    steps:["选择适合你需求的AI视频工具","创建或上传你的内容","使用AI增强、编辑或生成视频元素","迭代优化直到满意"],
    prompt:"我想用AI创建一个[视频类型]。帮我：\n1. 选择适合的AI工具组合\n2. 规划视频的每个元素\n3. 提供工作流程建议\n4. 给出最大化AI工具效果的技巧",
    promptTip:"最好的AI视频通常结合多个工具。用Runway生成片段，用CapCut编辑，用ElevenLabs添加旁白，用Suno创建背景音乐。",
    tools:["Runway","Kling","Pika","CapCut","Sora"],
    links:[{name:"Runway",url:"https://runwayml.com"},{name:"CapCut",url:"https://www.capcut.com"}]},

  {id:105, title:"克隆你的声音", subtitle:"用你的声音制作音频内容，无需每次都录制", category:"video",
    description:"AI语音克隆可以从短短几分钟的音频样本中复制你的声音。完成后，你可以输入任何文字生成听起来像你的旁白。这对创作者、教育者和需要高效制作大量语音内容的人来说是一个改变游戏规则的技术。",
    steps:["选择AI语音克隆工具（ElevenLabs是首选）","录制1-5分钟清晰、高质量的语音样本","上传样本并创建你的语音克隆","输入任何文字，用你的声音生成音频","微调设置以获得最自然的效果"],
    prompt:"我想用AI克隆我的声音用于[目的：YouTube视频旁白/播客/教育内容/有声书/个人项目]。\n\n请帮我：\n1. 选择最佳语音克隆工具\n2. 为获得最高质量的克隆准备我的语音样本\n3. 了解录音的最佳实践（设备、环境、说话方式）\n4. 这项技术的伦理考虑\n5. 如何优化克隆的自然度\n\n我特别想了解质量、成本和伦理使用方面的信息。",
    promptTip:"录音质量直接影响克隆效果。在安静的环境中使用好的麦克风录制。以正常语速清晰地说话。ElevenLabs只需30秒到5分钟的音频就能创建令人印象深刻的克隆。",
    tools:["ElevenLabs","Play.ht","Resemble AI","Descript"],
    links:[{name:"ElevenLabs",url:"https://elevenlabs.io"},{name:"Descript",url:"https://www.descript.com"}]},

  // ===== 生产力 (51-60) =====
  {id:51, title:"管理任务和项目", subtitle:"AI驱动的生产力系统", category:"productivity",
    description:"AI可以帮你组织任务、确定优先级和管理项目。从简单的待办清单到复杂的项目计划，AI让你保持在正轨上。",
    steps:["将你所有的任务和项目汇集在一起","请AI帮你确定优先级和组织","创建有里程碑的行动计划","定期与AI审查和调整"],
    prompt:"帮我组织和确定任务的优先级。这是我现在所有需要做的事情：\n\n[列出你所有的任务、截止日期和项目]\n\n请：\n1. 按紧急程度和重要性分类（艾森豪威尔矩阵）\n2. 建议每天的时间块安排\n3. 识别可以合并或委派的任务\n4. 创建本周的行动计划\n5. 建议保持动力的策略\n6. 标记可能的瓶颈或冲突",
    promptTip:"每周日晚花10分钟和AI一起规划下一周。用'2分钟法则'——如果能在2分钟内完成，现在就做。Notion或Todoist都是很好的任务管理工具。",
    tools:["ChatGPT","Claude","Notion","Todoist"],
    links:[{name:"Notion",url:"https://www.notion.so"},{name:"Todoist",url:"https://todoist.com"}]},

  {id:52, title:"总结文档和文章", subtitle:"快速获取关键信息", category:"productivity",
    description:"AI可以快速总结长文档、文章和报告——提取关键要点、主要论点和行动项目。节省数小时的阅读时间。",
    steps:["粘贴或上传文档","指定你需要什么类型的总结","审阅AI的摘要","请求对特定部分的深入解读"],
    prompt:"总结以下[文档/文章/报告]：\n\n[粘贴文字或描述文档]\n\n请提供：\n1. 一句话摘要\n2. 3-5个关键要点\n3. 主要论点和论据\n4. 任何行动项目或建议\n5. 我应该注意的重要数据或统计\n6. 100字的执行摘要\n\n还要标记你认为最重要但可能被忽视的信息。",
    promptTip:"对于很长的文档，逐部分提供给AI。请'先总结，然后告诉我哪些部分值得完整阅读'。这比全部读完再总结更高效。",
    tools:["ChatGPT","Claude","Gemini","Perplexity"],
    links:[{name:"ChatGPT",url:"https://chat.openai.com"},{name:"Claude",url:"https://claude.ai"}]},

  {id:53, title:"自动化重复性工作", subtitle:"让AI处理无聊的事情", category:"productivity",
    description:"AI可以帮你自动化许多重复性任务——从整理数据到生成报告再到回复模板邮件。将时间花在真正需要你的事情上。",
    steps:["识别你日常工作中的重复性任务","描述这些任务给AI","请AI创建自动化流程或模板","实施并节省时间"],
    prompt:"帮我自动化这些重复性任务：\n\n[描述你的重复性工作]\n\n对于每个任务，请：\n1. 建议最佳自动化方法\n2. 创建可重用的模板或脚本\n3. 推荐适合的工具\n4. 估计可以节省多少时间\n5. 提供逐步设置指南\n\n我的技术水平：[初学者/中级/高级]\n我使用的工具：[列出你当前使用的工具]",
    promptTip:"从最消耗时间的任务开始自动化。Zapier可以连接不同的应用程序并创建自动化流程。即使是简单的邮件模板也能节省大量时间。",
    tools:["ChatGPT","Zapier","Make","Google Apps Script"],
    links:[{name:"Zapier",url:"https://zapier.com"},{name:"Make",url:"https://www.make.com"}]},

  {id:54, title:"做笔记和组织知识", subtitle:"建立你的第二大脑", category:"productivity",
    description:"AI让笔记变得更强大。它可以帮你组织、连接和总结笔记——将散乱的信息变成有组织的知识库。建立你自己的'第二大脑'。",
    steps:["选择笔记工具（Notion、Obsidian等）","用AI帮助组织和标记笔记","创建知识之间的联系","定期用AI审阅和更新"],
    prompt:"帮我为[目的：课堂笔记/工作知识库/个人学习/研究项目]建立一个知识管理系统。\n\n我目前有关于这些话题的笔记：[列出话题]\n\n请：\n1. 建议最佳组织结构\n2. 创建类别和标签系统\n3. 建议如何连接相关概念\n4. 提供高效做笔记的模板\n5. 建议定期复习计划\n6. 推荐适合的工具",
    promptTip:"最好的笔记系统是你真正会使用的那个。从简单开始。Cornell笔记法是课堂笔记的好方法。用Notion或Obsidian创建互相连接的知识网络。",
    tools:["ChatGPT","Claude","Notion","Obsidian"],
    links:[{name:"Notion",url:"https://www.notion.so"},{name:"Obsidian",url:"https://obsidian.md"}]},

  {id:55, title:"创建电子表格和公式", subtitle:"AI让Excel和Sheets变得简单", category:"productivity",
    description:"不再为复杂的公式苦恼。AI可以为你编写Excel和Google Sheets公式、创建数据透视表，甚至构建完整的电子表格解决方案。",
    steps:["描述你想在电子表格中实现什么","请AI编写公式或创建结构","在表格中实施","请AI帮你解决问题或优化"],
    prompt:"帮我用[Excel/Google Sheets]解决这个问题：\n\n[描述你想做什么]\n\n我的数据看起来像这样：[描述你的数据结构]\n\n请提供：\n1. 完成任务所需的公式（带解释）\n2. 逐步设置说明\n3. 数据验证建议\n4. 格式化技巧使其更易读\n5. 如果合适，创建自动化宏\n\n我的Excel水平：[初学者/中级/高级]",
    promptTip:"学会VLOOKUP、IF和数据透视表——这三个就能解决80%的电子表格问题。请AI'解释这个公式的每个部分做什么'来学习。",
    tools:["ChatGPT","Claude","Google Sheets","Excel"],
    links:[{name:"Google Sheets",url:"https://sheets.google.com"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:56, title:"管理时间和日程", subtitle:"优化你的每一天", category:"productivity",
    description:"AI可以帮你创建高效的日程安排、时间块计划和习惯追踪系统。让每一天都更有生产力且平衡。",
    steps:["分享你目前的日程和目标","请AI分析和优化","实施建议的时间块计划","定期审阅和调整"],
    prompt:"帮我优化日程安排。目前情况：\n\n固定承诺：[列出——学校/工作时间、固定活动等]\n目标：[你想完成什么]\n挑战：[你面临的时间问题]\n能量模式：[你什么时候最有效率]\n\n请：\n1. 创建优化的每日日程\n2. 使用时间块技术安排任务\n3. 包含休息和休闲时间\n4. 建议处理拖延的策略\n5. 创建每周复习模板\n6. 推荐时间管理工具和方法",
    promptTip:"能量管理比时间管理更重要。把最难的任务安排在你最有精力的时候。用番茄工作法：25分钟专注+5分钟休息。",
    tools:["ChatGPT","Claude","Google Calendar","Todoist"],
    links:[{name:"Google Calendar",url:"https://calendar.google.com"},{name:"Todoist",url:"https://todoist.com"}]},

  {id:57, title:"准备面试", subtitle:"自信地面对任何面试", category:"productivity",
    description:"AI是终极面试教练。它可以生成常见问题、帮你准备STAR格式答案，甚至模拟整个面试过程——为你的大日子建立自信。",
    steps:["分享职位描述和你的背景","请AI生成可能的面试题","练习你的答案","模拟完整面试"],
    prompt:"帮我准备[职位名称]在[公司名称/行业]的面试。\n\n职位描述：[粘贴或描述]\n我的背景：[相关经验和技能]\n\n请：\n1. 列出15个最可能的面试问题\n2. 为最重要的5个问题提供STAR格式的示例答案\n3. 准备3个我应该问面试官的问题\n4. 建议如何回答'你的薪资期望是什么？'\n5. 提供穿着和肢体语言建议\n6. 模拟一个10分钟的面试，然后给出反馈",
    promptTip:"面试成功的关键是准备。练习大声说出答案，不只是在脑子里想。请AI进行'压力面试'——用刁难的问题训练你。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"ChatGPT",url:"https://chat.openai.com"},{name:"Glassdoor",url:"https://www.glassdoor.com"}]},

  {id:58, title:"做决策和分析选项", subtitle:"系统化地做出更好的决定", category:"productivity",
    description:"面对困难的选择？AI可以帮你系统地分析选项、权衡利弊、考虑你可能忽略的因素，并做出更明智的决定。",
    steps:["描述你需要做的决定","列出所有可能的选项","请AI进行结构化分析","基于分析做出明智选择"],
    prompt:"帮我做一个决定：[描述你面临的选择]。\n\n选项：\n1. [选项A]\n2. [选项B]\n3. [选项C（如果有）]\n\n考虑因素：[什么对你最重要]\n时间框架：[需要什么时候做出决定]\n\n请：\n1. 对每个选项进行优缺点分析\n2. 评估短期和长期影响\n3. 指出我可能忽略的因素\n4. 创建决策矩阵（对因素加权打分）\n5. 提出你的建议和理由\n6. 建议一个'试水'方法来降低风险",
    promptTip:"好的决策需要同时考虑逻辑和直觉。请AI先做分析，但也留意你的内心感受。对于重大决定，给自己一晚上'睡一觉再说'的时间。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"ChatGPT",url:"https://chat.openai.com"},{name:"Claude",url:"https://claude.ai"}]},

  {id:59, title:"研究和事实核查", subtitle:"快速找到可靠信息", category:"productivity",
    description:"AI可以帮你研究任何话题、汇总来自多个来源的信息，并帮助你辨别事实和虚假信息。像一个研究助手，但快了100倍。",
    steps:["定义你的研究问题","请AI搜索和汇总信息","验证关键事实的来源","请AI标记不确定或有争议的信息"],
    prompt:"帮我研究[话题]。目的：[为什么你在研究——论文/项目/好奇心/决策]。\n\n请：\n1. 提供全面的概述\n2. 包括关键事实和统计数据\n3. 呈现不同的观点\n4. 引用信息来源\n5. 标记任何有争议或不确定的信息\n6. 建议进一步阅读的资源\n7. 创建研究摘要以供参考\n\n重要：明确区分已确认的事实和观点。",
    promptTip:"始终交叉验证AI提供的关键信息。使用Perplexity获取带来源的回答。对于学术研究，使用Google Scholar找原始论文。AI是研究的起点，不是终点。",
    tools:["Perplexity","ChatGPT","Claude","Google Scholar"],
    links:[{name:"Perplexity",url:"https://perplexity.ai"},{name:"Google Scholar",url:"https://scholar.google.com"}]},

  {id:60, title:"规划目标和习惯", subtitle:"用AI建立改变人生的习惯", category:"productivity",
    description:"AI可以帮你设定清晰的目标、建立可持续的习惯，并创建问责系统。把大目标分解成每天的小行动。",
    steps:["定义你的目标","请AI帮你创建具体的行动计划","建立每日习惯追踪","定期与AI审视进展"],
    prompt:"帮我实现这个目标：[你的目标]。\n\n时间框架：[什么时候要实现]\n当前情况：[你现在在哪里]\n过去的挑战：[为什么之前没成功]\n\n请：\n1. 把目标分解成SMART子目标\n2. 创建每日/每周的习惯清单\n3. 设计一个30天的启动计划\n4. 包含里程碑和奖励\n5. 建议处理动力下降的策略\n6. 创建一个简单的追踪系统\n7. 预测并预防常见的失败点",
    promptTip:"从小开始——'每天运动5分钟'比'每天运动1小时'更容易坚持。习惯叠加效果好：把新习惯附加在已有的习惯上。用Habitica把习惯变成游戏。",
    tools:["ChatGPT","Claude","Habitica","Notion"],
    links:[{name:"Habitica",url:"https://habitica.com"},{name:"Notion",url:"https://www.notion.so"}]},

  // ===== 编程与技术 (61-70) =====
  {id:61, title:"构建网站", subtitle:"从零开始用AI创建网站", category:"coding",
    description:"AI可以帮你构建完整的网站——从HTML/CSS到JavaScript。描述你想要什么，AI就能生成代码。非常适合作品集、项目和学习网页开发。",
    steps:["描述你想要的网站","请AI生成HTML/CSS/JS代码","在浏览器中预览并测试","迭代改进设计和功能"],
    prompt:"帮我创建一个[类型：个人作品集/登录页/博客/项目展示/在线商店]网站。\n\n要求：\n- 设计风格：[极简/现代/有趣/专业]\n- 页面：[列出需要的页面]\n- 功能：[列出需要的功能]\n- 配色方案：[描述或让AI建议]\n- 响应式：必须在手机上好看\n\n请用HTML、CSS和JavaScript创建完整的代码，作为一个自包含的文件。解释代码的每个主要部分。",
    promptTip:"从简单的单页网站开始，然后逐步添加功能。用GitHub Pages免费发布你的网站。请AI'让这个网站在手机上也好看'来确保响应式设计。",
    tools:["ChatGPT","Claude","Replit","VS Code"],
    links:[{name:"Replit",url:"https://replit.com"},{name:"GitHub Pages",url:"https://pages.github.com"}]},

  {id:62, title:"创建应用程序", subtitle:"构建你自己的软件", category:"coding",
    description:"有了AI作为你的编程伙伴，创建应用程序变得前所未有的容易。从简单的工具到功能丰富的应用，AI帮你在每一步中编写、调试和优化代码。",
    steps:["描述你的应用创意","选择技术栈（AI可以建议）","与AI一起逐步构建","测试、调试并部署"],
    prompt:"帮我创建一个[类型：网页应用/手机应用/桌面工具/Chrome扩展]。\n\n应用描述：[它应该做什么]\n主要功能：[列出功能]\n技术偏好：[Python/JavaScript/等或让AI建议]\n用户：[谁会使用它]\n\n请：\n1. 建议最佳技术栈\n2. 创建项目结构\n3. 从核心功能开始编写代码\n4. 包含错误处理\n5. 添加评论解释代码\n6. 提供测试和部署指南",
    promptTip:"从MVP（最小可行产品）开始——只实现核心功能。让它工作了再美化。请AI'审查这段代码的安全问题'来避免常见漏洞。",
    tools:["ChatGPT","Claude","Replit","VS Code"],
    links:[{name:"Replit",url:"https://replit.com"},{name:"VS Code",url:"https://code.visualstudio.com"}]},

  {id:63, title:"调试和修复代码", subtitle:"让AI帮你找到Bug", category:"coding",
    description:"卡在Bug上？AI是出色的调试伙伴。它可以分析你的代码、找出问题、解释根本原因并提供修复方案——通常比自己搜索解决方案快得多。",
    steps:["粘贴出错的代码和错误信息","描述期望行为和实际行为","请AI分析问题","应用修复并从错误中学习"],
    prompt:"帮我调试这段代码：\n\n```[语言]\n[你的代码]\n```\n\n问题：[描述出了什么问题]\n错误信息：[如果有的话，粘贴完整的错误信息]\n期望行为：[它应该做什么]\n实际行为：[它实际做了什么]\n\n请：\n1. 找出具体的Bug\n2. 解释为什么会发生\n3. 提供修复后的代码\n4. 解释修复的内容\n5. 建议如何防止类似的Bug\n6. 建议相关的代码改进",
    promptTip:"提供错误信息和上下文越多，AI的诊断越准确。学会阅读错误信息——它们通常直接告诉你问题在哪里。使用print/console.log来追踪代码执行流程。",
    tools:["ChatGPT","Claude","GitHub Copilot","Stack Overflow"],
    links:[{name:"Stack Overflow",url:"https://stackoverflow.com"},{name:"GitHub Copilot",url:"https://github.com/features/copilot"}]},

  {id:64, title:"学习数据结构和算法", subtitle:"掌握编程面试的基础", category:"coding",
    description:"数据结构和算法是计算机科学的基础。AI可以用可视化解释、逐步示例和练习题帮你掌握这些概念。",
    steps:["选择一个数据结构或算法学习","请AI用可视化方式解释","用代码示例实践","解决越来越难的练习题"],
    prompt:"教我[数据结构/算法：链表/树/图/排序/搜索/动态规划]。\n\n我的水平：[初学者/知道基础/准备面试]\n偏好语言：[Python/JavaScript/Java/C++]\n\n请：\n1. 用日常类比解释概念\n2. 展示可视化的工作过程\n3. 提供从零实现的代码\n4. 解释时间和空间复杂度\n5. 给出3道递增难度的练习题\n6. 展示这在面试中如何出现",
    promptTip:"不要只是读代码——自己打出来并运行。LeetCode是练习算法题的最佳平台。从简单题开始，不要直接跳到困难题。",
    tools:["ChatGPT","Claude","LeetCode","Visualgo"],
    links:[{name:"LeetCode",url:"https://leetcode.com"},{name:"Visualgo",url:"https://visualgo.net"}]},

  {id:65, title:"创建游戏", subtitle:"用代码构建你的第一个游戏", category:"coding",
    description:"游戏开发是学习编程最有趣的方式之一。AI可以帮你从简单的猜数字游戏到完整的2D平台游戏——一步一步来。",
    steps:["选择游戏类型和复杂度","让AI帮你设计游戏机制","逐步编写代码","测试、调试并添加新功能"],
    prompt:"帮我用[语言/工具：Python/JavaScript/Unity/Godot]创建一个[类型：猜数字/贪吃蛇/平台跳跃/射击/益智]游戏。\n\n复杂度：[简单/中等/高级]\n\n请：\n1. 设计游戏机制和规则\n2. 创建基本的游戏框架代码\n3. 添加玩家控制\n4. 实现得分系统\n5. 添加难度递增\n6. 解释代码中的每个主要部分\n\n从最简单的可玩版本开始，然后再添加功能。",
    promptTip:"游戏开发中最常见的错误是一开始就太复杂。先让核心玩法工作（移动和碰撞），然后逐步添加其他功能。JavaScript+HTML5 Canvas是最容易入门的平台。",
    tools:["ChatGPT","Claude","Replit","Unity"],
    links:[{name:"Replit",url:"https://replit.com"},{name:"Unity",url:"https://unity.com"}]},

  {id:66, title:"构建聊天机器人", subtitle:"创建你自己的AI助手", category:"coding",
    description:"学习如何构建你自己的聊天机器人——从简单的规则型到集成AI的智能对话系统。一个出色的项目来展示你的技能。",
    steps:["定义你的聊天机器人的目的和功能","选择平台和技术","用AI帮助编写代码","测试并持续改进"],
    prompt:"帮我构建一个[类型：客服/信息查询/娱乐/个人助手]聊天机器人。\n\n平台：[网页/Discord/Telegram/WhatsApp]\n技术：[Python/JavaScript/低代码]\n功能：[列出你想要机器人做什么]\n\n请：\n1. 设计对话流程\n2. 编写核心代码\n3. 处理常见用户输入\n4. 添加错误处理\n5. 提供部署指南\n6. 建议改进方向",
    promptTip:"从简单的对话流程开始。一个能很好回答5个常见问题的机器人比一个试图做所有事但做不好的机器人有用得多。",
    tools:["ChatGPT","Claude","Python","Botpress"],
    links:[{name:"Botpress",url:"https://botpress.com"},{name:"Replit",url:"https://replit.com"}]},

  {id:67, title:"分析和可视化数据", subtitle:"把数据变成洞察", category:"coding",
    description:"AI让数据分析变得更容易。从清洗数据到创建漂亮的可视化——AI可以用Python帮你完成通常需要专业数据科学家才能做到的工作。",
    steps:["准备你的数据集","用AI清洗和处理数据","创建有洞察力的可视化","解读结果并讲述数据故事"],
    prompt:"帮我分析这个数据集：[描述你的数据]。\n\n数据列：[列出列名和类型]\n我想了解：[你的问题]\n\n请：\n1. 建议数据清洗步骤\n2. 进行探索性数据分析\n3. 创建有意义的可视化（用Python matplotlib/seaborn）\n4. 找出关键模式和洞察\n5. 提供可执行的建议\n6. 生成可以在Jupyter notebook中运行的完整代码",
    promptTip:"数据分析的80%是清洗数据。请AI帮你'检查这个数据集的质量问题'。Google Colab是免费运行Python数据分析的最佳环境。",
    tools:["ChatGPT","Claude","Python","Google Colab"],
    links:[{name:"Google Colab",url:"https://colab.research.google.com"},{name:"Kaggle",url:"https://www.kaggle.com"}]},

  {id:68, title:"学习Git和版本控制", subtitle:"像专业人士一样管理代码", category:"coding",
    description:"Git是每个程序员必须掌握的工具。AI可以用简单的语言解释Git概念，帮你解决Git问题，并指导你的版本控制工作流程。",
    steps:["学习Git的基本概念","用AI指导完成第一个Git工作流程","练习常见操作","学习处理合并冲突和高级功能"],
    prompt:"做我的Git导师。我是[水平：完全初学者/知道基础/想学高级功能]。\n\n请：\n1. 用简单类比解释Git的核心概念\n2. 教我必须掌握的10个Git命令\n3. 带我完成一个完整的Git工作流程（从创建仓库到推送代码）\n4. 解释分支、合并和Pull Request\n5. 展示如何解决合并冲突\n6. 分享常见Git错误及修复方法",
    promptTip:"把Git想象成'撤销历史'——你可以随时回到代码的任何过去版本。GitHub Desktop是初学者的好工具——图形界面比命令行容易上手。",
    tools:["ChatGPT","Claude","GitHub","VS Code"],
    links:[{name:"GitHub",url:"https://github.com"},{name:"Git教程",url:"https://learngitbranching.js.org"}]},

  {id:69, title:"构建API和后端", subtitle:"创建应用的服务器端", category:"coding",
    description:"API和后端是大多数应用的核心。AI可以帮你设计、构建和部署API——从简单的REST API到数据库集成。",
    steps:["定义你的API需要什么功能","选择后端技术（AI可以建议）","与AI一起构建","测试并部署"],
    prompt:"帮我构建一个[用途]的后端API。\n\n技术栈：[Node.js/Python Flask/Python FastAPI/等或让AI建议]\n功能：[列出端点和操作]\n数据：[需要存储什么数据]\n\n请：\n1. 设计API端点和数据模型\n2. 编写完整的API代码\n3. 添加输入验证和错误处理\n4. 包含身份验证（如果需要）\n5. 提供测试方法\n6. 建议部署平台",
    promptTip:"从最少的端点开始——先让CRUD（创建、读取、更新、删除）操作工作。用Postman测试API。Render和Railway提供免费的后端部署。",
    tools:["ChatGPT","Claude","Replit","Postman"],
    links:[{name:"Postman",url:"https://www.postman.com"},{name:"Render",url:"https://render.com"}]},

  {id:70, title:"学习网络安全基础", subtitle:"保护自己在数字世界中安全", category:"coding",
    description:"了解网络安全对每个人都很重要——不仅仅是技术人员。AI可以教你保护自己免受黑客、钓鱼和数据泄露的方法。",
    steps:["学习基本的安全概念","用AI了解常见的攻击类型","练习保护你自己的账户","学习如何识别和避免威胁"],
    prompt:"做我的网络安全导师。教我[水平：个人安全基础/网页安全/网络安全/道德黑客入门]。\n\n请：\n1. 解释今天最常见的网络威胁\n2. 教我如何保护我的在线账户\n3. 演示钓鱼邮件的常见特征\n4. 解释加密是什么以及为什么重要\n5. 创建一个个人安全检查清单\n6. 推荐进一步学习的资源\n\n用实际例子说明——不要太理论化。",
    promptTip:"最重要的三件事：使用密码管理器、开启二步验证、不要点击可疑链接。Bitwarden是免费开源的密码管理器。Have I Been Pwned可以检查你的邮箱是否在数据泄露中。",
    tools:["ChatGPT","Claude","CyberChef","HackTheBox"],
    links:[{name:"Have I Been Pwned",url:"https://haveibeenpwned.com"},{name:"HackTheBox",url:"https://www.hackthebox.com"}]},

  {id:104, title:"在GitHub上发布免费网站", subtitle:"与世界分享你的AI创作", category:"coding",
    description:"GitHub Pages让你可以将任何HTML文件发布为一个实时网站——完全免费。这是分享你的互动AI创作的完美方式：游戏、测验、作品集、应用等。无需托管费，无需服务器配置。只需上传文件就能获得一个任何人都能访问的链接。",
    steps:["在github.com创建免费账户","创建一个新的公开仓库","上传你的HTML文件（命名为index.html）","进入Settings → Pages，选择'main'分支并保存","你的网站已在yourusername.github.io/repo-name/上线"],
    prompt:"我使用AI创建了一个互动[类型：游戏/测验/网站/应用/作品集]作为单个HTML文件。帮我一步步在GitHub Pages上发布它。我是完全的初学者，从未使用过GitHub。\n\n请解释：\n1. 如何创建GitHub账户\n2. 如何创建仓库\n3. 如何上传我的文件\n4. 如何启用GitHub Pages\n5. 如何分享链接\n6. 以后如何更新网站\n7. 如何使用自定义域名（可选）\n\n请用简单语言——我不了解任何编程术语。",
    promptTip:"将主文件命名为'index.html'——这是GitHub Pages的关键。你可以托管多个页面甚至添加图片。要获得干净的URL，考虑将仓库命名为'yourusername.github.io'。",
    tools:["GitHub Pages","ChatGPT","Claude"],
    links:[{name:"GitHub Pages",url:"https://pages.github.com"},{name:"GitHub",url:"https://github.com"}]},

  {id:107, title:"用Mermaid创建图表", subtitle:"从文字到流程图、时间线等", category:"coding",
    description:"Mermaid是一种简单的基于文本的语言，AI可以为你编写来创建美观的图表——流程图、序列图、时间线、思维导图、甘特图等。只需描述你需要什么，AI就能生成Mermaid代码。粘贴到任何Mermaid查看器中，就能立即获得专业图表。",
    steps:["描述你需要的图表（流程图、时间线、过程等）","请AI为其生成Mermaid代码","将代码粘贴到Mermaid在线编辑器或兼容工具中","导出为图像或嵌入到文档中"],
    prompt:"为[描述：登录流程的流程图/法国大革命的时间线/API调用的序列图/团队的组织结构图/AI应用的思维导图]创建一个Mermaid图表。\n\n要求：\n- 使用清晰易读的标签\n- 添加颜色或样式来突出关键元素\n- 包含所有主要步骤/节点\n- 让流程易于跟踪\n\n给我可以直接粘贴到Mermaid Live Editor中的Mermaid代码。",
    promptTip:"使用Mermaid Live Editor（mermaid.live）即时预览和导出图表。GitHub也在Markdown文件中原生渲染Mermaid图表。Claude和ChatGPT都能写出出色的Mermaid代码。",
    tools:["Claude","ChatGPT","Mermaid Live Editor","GitHub"],
    links:[{name:"Mermaid Live Editor",url:"https://mermaid.live"},{name:"Mermaid文档",url:"https://mermaid.js.org"}]},

  // ===== 商业与创业 (71-80) =====
  {id:71, title:"创建商业计划", subtitle:"构建你的创业想法", category:"business",
    description:"有商业想法？AI可以帮你撰写专业的商业计划，涵盖市场分析、财务预测、营销策略等。非常适合学校项目或真正的创业。",
    steps:["详细描述你的商业想法","请AI创建结构化的商业计划","研究并验证关键假设","完善并展示你的计划"],
    prompt:"为[商业创意]创建商业计划。包括：\n- 执行摘要\n- 问题和解决方案\n- 目标市场（规模、人口特征、需求）\n- 价值主张\n- 收入模式（如何赚钱）\n- 营销策略\n- 竞争分析（3个竞争对手）\n- 所需团队结构\n- 财务预测（第一年）\n- 主要风险和应对措施\n\n要专业但清晰到足以用于学校演示。",
    promptTip:"从你要解决的问题开始——这是最重要的部分。请AI'给这个商业计划挑毛病'以获得诚实的反馈。",
    tools:["ChatGPT","Claude","Gemini","Perplexity"],
    links:[{name:"Lean Canvas",url:"https://leanstack.com/lean-canvas"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:72, title:"制定营销策略", subtitle:"有效地触达你的受众", category:"business",
    description:"AI可以创建针对你的产品、预算和目标受众量身定制的综合营销策略。从社交媒体到内容营销再到增长黑客。",
    steps:["定义你的产品/服务和目标受众","请AI创建营销策略","选择适合你预算的渠道和策略","创建内容日历并执行"],
    prompt:"为[产品/服务/品牌]创建营销策略，面向[受众：青少年/年轻人/等]在[地区/市场]。预算：[低/中/高或具体金额]。包括：\n- 需要关注的前3个营销渠道\n- 内容策略（发什么、多频繁）\n- 社交媒体计划\n- 互动策略\n- 增长黑客创意\n- 需要跟踪的关键指标\n- 30天行动计划",
    promptTip:"集中精力在最多2-3个渠道上，而不是什么都尝试。请AI提供'零预算的游击营销创意'来获得创造性方案。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"HubSpot",url:"https://www.hubspot.com"},{name:"Canva",url:"https://www.canva.com"}]},

  {id:73, title:"设计路演演示", subtitle:"令人信服地展示你的想法", category:"business",
    description:"出色的路演演示可以赢得投资者、合作伙伴或比赛评委。AI帮你构建演示结构、撰写引人注目的文案和设计有说服力的幻灯片。",
    steps:["定义你的演示：向谁展示，为什么","请AI构建10-12张幻灯片","为每张幻灯片创建关键信息","练习你的演讲"],
    prompt:"为[想法/公司]创建一个[数量]张幻灯片的路演演示，面向[受众：投资者/评委/班级/潜在合作伙伴]。包括以下幻灯片：\n1. 标题幻灯片（吸引人的标语）\n2. 问题\n3. 解决方案\n4. 市场规模\n5. 如何运作\n6. 牵引力/证明\n7. 商业模式\n8. 竞争\n9. 团队\n10. 诉求（你需要什么）\n\n为每张幻灯片提供关键信息、演讲要点和建议的视觉效果。",
    promptTip:"每张幻灯片只表达一个想法。使用10-20-30法则：10张幻灯片，20分钟，最小30号字体。练习讲故事，而不是读幻灯片。",
    tools:["ChatGPT","Claude","Canva","Gamma"],
    links:[{name:"Gamma",url:"https://gamma.app"},{name:"Canva演示文稿",url:"https://www.canva.com/presentations"}]},

  {id:74, title:"分析市场趋势", subtitle:"了解你的市场", category:"business",
    description:"AI可以研究和分析市场趋势，帮你了解行业动态、新兴机会和潜在威胁。对任何商业想法或学校项目都不可或缺。",
    steps:["定义你想分析的市场或行业","请AI研究当前趋势","审查数据来源并验证发现","创建市场分析报告"],
    prompt:"分析[行业/市场]在[地区/全球]的当前市场趋势。包括：\n- 市场规模和增长率\n- 当前的5大趋势\n- 新兴技术或颠覆\n- 消费者行为变化\n- 主要参与者及其市场份额\n- 新进入者的机会\n- 威胁和挑战\n- 未来2-3年的预测\n\n说明你的推理并建议在哪里找到更新的数据。",
    promptTip:"使用Perplexity获取带来源的最新市场数据。将AI洞察与实际行业报告交叉验证。问'我应该检查哪些数据来源来验证这些？'",
    tools:["Perplexity","ChatGPT","Claude","Gemini"],
    links:[{name:"Perplexity",url:"https://perplexity.ai"},{name:"Statista",url:"https://www.statista.com"}]},

  {id:75, title:"创建财务预测", subtitle:"规划你的财务", category:"business",
    description:"AI可以帮你构建财务模型、预测收入、估算成本和创建商业计划的财务部分。即使你不是金融专家。",
    steps:["描述你的商业模式和收入来源","提供任何成本估算","请AI创建财务预测","构建电子表格并调整假设"],
    prompt:"为[企业]创建12个月的财务预测，基于以下假设：\n- 收入模式：[如何赚钱]\n- 预期每月客户数：[从X增长到Y]\n- 平均价格：[价格]\n- 每月固定成本：[列表]\n- 可变成本：[单位成本]\n\n提供：月收入、成本、利润/亏损、盈亏平衡分析和现金流。格式化为可以复制到电子表格中的表格。",
    promptTip:"收入估计保守些，成本估计大方些。始终包含'悲观'和'乐观'场景以及基本情况。",
    tools:["ChatGPT","Claude","Google Sheets","Excel"],
    links:[{name:"Google Sheets",url:"https://sheets.google.com"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:76, title:"撰写产品描述", subtitle:"用文字有效地销售", category:"business",
    description:"出色的产品描述能卖货。AI可以写出引人注目、有说服力的产品文案，突出优势、回应客户顾虑并推动行动。",
    steps:["描述你的产品：功能、优势、目标受众","指定语气和平台","请AI写多个描述版本","测试哪个效果最好"],
    prompt:"为面向[受众]的[产品]写3个产品描述。每个版本应该是：\n1. 短版（50字）——社交媒体用\n2. 中版（150字）——在线商店用\n3. 长版（300字）——详细产品页面用\n\n突出：[关键优势]。语气：[有趣/专业/奢华/环保]。包含引人注目的行动号召。注重优势而非功能。",
    promptTip:"优势卖货，功能告知。与其说'用回收材料制成'（功能），不如写'知道你在保护地球，感觉很好'（优势）。",
    tools:["ChatGPT","Claude","Jasper","Gemini"],
    links:[{name:"ChatGPT",url:"https://chat.openai.com"},{name:"Shopify",url:"https://www.shopify.com"}]},

  {id:77, title:"生成品牌名称", subtitle:"找到完美的名字", category:"business",
    description:"为品牌、项目或产品取名出人意料地困难。AI可以头脑风暴创意名称、检查域名可用性概念，并解释每个名称背后的心理学。",
    steps:["描述你的品牌：价值观、受众、行业","请AI生成20-30个名称选项","筛选到前5名","检查域名和社交媒体可用性"],
    prompt:"为[商业类型/产品]生成20个有创意的品牌名称。品牌应该感觉[形容词：现代/可信/有趣/奢华/科技感/环保]。目标受众：[受众]。行业：[行业]。\n\n为每个名称提供：\n- 名称\n- 为什么有效\n- 潜在的.com域名可用性（如果被占用建议替代方案）\n- 作为社交媒体用户名的效果\n\n包含混合：造词、复合词、隐喻和简短好记的名称。",
    promptTip:"在Namecheap或GoDaddy上检查域名可用性。在Instagram和TikTok上搜索用户名可用性。最好的名称是简短、好记且容易拼写的。",
    tools:["ChatGPT","Claude","Namecheap","Namelix"],
    links:[{name:"Namecheap",url:"https://www.namecheap.com"},{name:"Namelix",url:"https://namelix.com"}]},

  {id:78, title:"创建客户调查", subtitle:"收集有价值的反馈", category:"business",
    description:"设计良好的调查可以揭示客户的真实想法。AI可以创建专业的调查，包含正确的问题类型、流程和分析框架。",
    steps:["定义你想了解什么","请AI设计调查","在Google表单或Typeform中创建","用AI帮助分析结果"],
    prompt:"为[产品/服务/项目]创建一个[长度：5/10/15]题的客户调查。目标：[想了解什么]。包括：\n- 不同问题类型的混合（选择题、评分量表、开放题）\n- 从简单到复杂的逻辑流程\n- 没有引导性或偏见性的问题\n- 简短友好的介绍\n- 结尾的感谢信息\n\n另外建议：如何分发以及结果中要注意什么。",
    promptTip:"调查保持在5分钟以内（最多10题）。最重要的问题放在前面。提供完成奖励。Google表单是免费的。",
    tools:["ChatGPT","Claude","Google Forms","Typeform"],
    links:[{name:"Google Forms",url:"https://forms.google.com"},{name:"Typeform",url:"https://www.typeform.com"}]},

  {id:79, title:"分析竞争对手", subtitle:"了解你的市场格局", category:"business",
    description:"了解竞争对手对任何商业或项目都至关重要。AI可以帮你研究竞争对手、识别他们的优势和劣势，并找到你的竞争优势。",
    steps:["确定你的3-5个主要竞争对手","请AI研究每一个","创建比较矩阵","识别差距和机会"],
    prompt:"为[你的业务/想法]对以下竞争对手进行竞争分析：[列出竞争对手]。对每个竞争对手分析：\n- 他们提供什么\n- 他们的优势和劣势\n- 定价策略\n- 目标受众\n- 营销方法\n- 客户评价/声誉\n\n然后创建比较表并识别：\n- 我们可以填补的市场空白\n- 我们潜在的竞争优势\n- 需要注意的威胁",
    promptTip:"在请AI分析之前，先访问竞争对手的网站和社交媒体。你提供的背景越多，分析越好。问'什么能让我们比[竞争对手]好10倍？'",
    tools:["Perplexity","ChatGPT","Claude","Gemini"],
    links:[{name:"Perplexity",url:"https://perplexity.ai"},{name:"SimilarWeb",url:"https://www.similarweb.com"}]},

  {id:80, title:"起草商业沟通", subtitle:"适合任何场景的专业写作", category:"business",
    description:"从合作提案到投资者更新再到客户公告，AI帮你撰写专业的商业沟通内容，给人留下正确的印象。",
    steps:["定义目的、收件人和期望结果","指定语气和格式","请AI起草沟通内容","审阅、个性化并发送"],
    prompt:"起草一份[类型：合作提案/投资者更新/客户公告/新闻稿/LinkedIn帖子]关于[话题]。收件人：[谁]。关键信息：[要点]。期望结果：[你想让他们做什么]。\n\n语气：[专业/友好/紧急/鼓舞人心]。长度：[短/中/长]。包括：\n- 有力的开头\n- 清晰的价值主张\n- 支撑细节\n- 明确的行动号召\n- 专业的结尾",
    promptTip:"始终个性化AI生成的商业沟通。添加具体的姓名、日期和引用。大声朗读检查是否自然。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"ChatGPT",url:"https://chat.openai.com"},{name:"Claude",url:"https://claude.ai"}]},

  // ===== 科学与研究 (81-90) =====
  {id:81, title:"分析数据集", subtitle:"在数据中发现模式", category:"science",
    description:"AI可以帮你分析数据——从发现模式到运行统计检验再到识别异常值。非常适合科学项目、调查或任何你需要理解的数据。",
    steps:["准备数据（清洗和整理）","描述数据和你想发现什么","请AI建议和执行分析","用AI帮助解读结果"],
    prompt:"我有一个关于[主题]的数据集，包含以下列：[列出列和数据类型]。我想：\n1. 找出主要模式和趋势\n2. 识别[变量A]和[变量B]之间的相关性\n3. 计算基本统计量（均值、中位数、标准差）\n4. 识别异常值\n5. 创建关键发现的摘要\n\n请建议适当的统计检验并写Python代码来执行分析。",
    promptTip:"先清洗数据：去重、处理缺失值。分析后请AI'用简单语言解释这些结果'。始终质疑相关性是否意味着因果关系。",
    tools:["ChatGPT","Claude","Python","Google Sheets"],
    links:[{name:"Google Colab",url:"https://colab.research.google.com"},{name:"Kaggle",url:"https://www.kaggle.com"}]},

  {id:82, title:"创建科学模型", subtitle:"用AI模拟世界", category:"science",
    description:"AI可以帮你构建数学和计算模型来模拟科学现象——从人口增长到化学反应再到物理模拟。",
    steps:["定义你想模拟什么","确定变量和关系","请AI创建数学模型","用Python或电子表格实现并可视化"],
    prompt:"帮我创建一个[现象：人口增长/疾病传播/钟摆运动/化学反应/气候变化因素]的科学模型。包括：\n1. 关键变量和参数\n2. 数学方程\n3. 假设和限制\n4. Python模拟代码\n5. 结果可视化\n6. 如何调整参数探索不同场景",
    promptTip:"从简单模型开始，逐步增加复杂度。使用Google Colab（免费）运行Python模拟。请AI帮助用真实数据验证你的模型。",
    tools:["Claude","ChatGPT","Python","MATLAB"],
    links:[{name:"Google Colab",url:"https://colab.research.google.com"},{name:"PhET Simulations",url:"https://phet.colorado.edu"}]},

  {id:83, title:"生成研究摘要", subtitle:"快速消化学术论文", category:"science",
    description:"学术论文可能晦涩难懂。AI可以总结研究论文、解释方法论、突出关键发现，并用你能理解的语言呈现结果。",
    steps:["找到研究论文或文章","粘贴摘要或关键部分","请AI用简单语言总结","要求解释特定部分"],
    prompt:"为高中生总结这篇研究论文：\n\n[粘贴摘要或关键文本]\n\n请提供：\n1. 研究者试图回答什么问题\n2. 他们如何研究（方法，简化版）\n3. 发现了什么（关键结果）\n4. 为什么重要（意义）\n5. 研究的局限性\n6. 这与已有知识的联系\n\n用简单语言，不要专业术语。",
    promptTip:"使用Semantic Scholar或Google Scholar查找论文。如果全文太长，粘贴摘要和结论。对不清楚的地方提出后续问题。",
    tools:["Claude","ChatGPT","Perplexity","Semantic Scholar"],
    links:[{name:"Semantic Scholar",url:"https://www.semanticscholar.org"},{name:"Google Scholar",url:"https://scholar.google.com"}]},

  {id:84, title:"可视化科学数据", subtitle:"清晰地呈现发现", category:"science",
    description:"数据可视化在科学中至关重要。AI可以帮你为数据创建正确类型的图表、生成代码，并使其达到报告和演示的专业级别。",
    steps:["准备数据","选择正确的可视化类型","请AI创建图表代码","自定义颜色、标签和格式"],
    prompt:"我需要可视化[描述你的数据和想展示什么]。使用Python（matplotlib或seaborn）创建一个[图表类型]。要求：\n- 清晰专业的外观\n- 带单位的正确轴标签\n- 描述性标题\n- 色盲友好的配色方案\n- 如果有多个数据系列则添加图例\n- 如适用添加误差棒\n\n数据：[提供数据或格式]",
    promptTip:"选择正确的图表：散点图用于相关性，柱状图用于比较，折线图用于时间序列，直方图用于分布。使用seaborn可获得更美观的默认效果。",
    tools:["Claude","ChatGPT","Python","Google Sheets"],
    links:[{name:"Google Colab",url:"https://colab.research.google.com"},{name:"Plotly",url:"https://plotly.com"}]},

  {id:85, title:"模拟实验", subtitle:"虚拟实验室工作", category:"science",
    description:"无法使用实验室？AI可以帮你模拟实验、预测结果，并通过计算模型和模拟来理解科学过程。",
    steps:["定义你想模拟的实验","指定变量和条件","请AI创建模拟","分析虚拟结果并得出结论"],
    prompt:"模拟一个实验：[描述实验]。变量：\n- 自变量：[你改变什么]\n- 因变量：[你测量什么]\n- 控制变量：[保持不变的]\n\n请：\n1. 根据科学理论预测预期结果\n2. 写一个Python模拟来建模此实验\n3. 生成近似真实结果的数据\n4. 创建结果可视化\n5. 解释真实结果可能与模拟有何不同",
    promptTip:"PhET（科罗拉多大学）有出色的免费物理和化学模拟。将PhET模拟与AI分析结合以获得更深入的理解。",
    tools:["Claude","ChatGPT","Python","PhET"],
    links:[{name:"PhET Simulations",url:"https://phet.colorado.edu"},{name:"Google Colab",url:"https://colab.research.google.com"}]},

  {id:86, title:"撰写实验报告", subtitle:"正确记录你的发现", category:"science",
    description:"写得好的实验报告遵循特定结构。AI可以帮你正确撰写每个部分，从摘要到讨论，确保你符合科学写作标准。",
    steps:["收集你的实验数据和观察","请AI帮助构建每个部分","按模板撰写报告","请AI审查完整性和清晰度"],
    prompt:"帮我为关于[实验主题]的实验撰写实验报告。我进行了[简要描述]。我的结果是[结果摘要]。\n\n创建结构正确的实验报告：\n1. 标题\n2. 摘要（100字）\n3. 引言（背景、假设）\n4. 材料和方法\n5. 结果（如何呈现数据）\n6. 讨论（结果含义、误差、改进）\n7. 结论\n\n使用正式的科学写作风格。",
    promptTip:"永远不要编造数据。用AI帮助结构化和清晰写作，但你的数据和观察必须是真实的。请AI'找出我方法论中的弱点'以获得更好的分析。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"Google Docs",url:"https://docs.google.com"}]},

  {id:87, title:"创建科学海报", subtitle:"会议级别的展示", category:"science",
    description:"科学海报需要清晰且视觉化地传达复杂的研究。AI可以帮你设计布局、撰写简洁文本和创建专业海报的图表。",
    steps:["将研究总结为海报各部分","请AI提供布局和设计建议","创建图表和图形","使用Canva或PowerPoint组装"],
    prompt:"帮我为[研究主题]创建科学海报。我的主要发现是[摘要]。设计海报包含：\n- 标题和作者部分\n- 引言/背景（3-4句话）\n- 方法（简要，附图表建议）\n- 结果（描述关键图表）\n- 讨论/结论（3-4个要点）\n- 参考文献\n\n建议专业且在1.2米外容易阅读的配色方案和布局。标准海报尺寸：120x90厘米。",
    promptTip:"海报上文字越少越好。用图表和图形作为主要内容。保持字体大小可读：标题72pt+，正文28pt+，说明20pt+。用Canva轻松组装。",
    tools:["ChatGPT","Claude","Canva","PowerPoint"],
    links:[{name:"Canva",url:"https://www.canva.com"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:88, title:"生成假设", subtitle:"正确开始你的研究", category:"science",
    description:"科学方法从一个好的假设开始。AI可以帮你根据观察、现有研究和科学原理生成可检验的假设。",
    steps:["描述你的观察或研究问题","请AI建议可检验的假设","评估每个假设的可检验性","为实验选择最佳假设"],
    prompt:"我对研究[主题/观察]感兴趣。帮我制定一个强有力的科学假设：\n1. 基于已有知识，建议3个可检验的假设\n2. 对每个假设提供：\n   - 假设陈述（如果...那么...因为...）\n   - 需要检验的变量\n   - 如何设计实验来检验它\n   - 什么结果会支持或反驳它\n3. 哪个假设对高中生来说最可行？",
    promptTip:"好的假设是具体的、可检验的、基于现有知识的。使用'如果[我做X]，那么[Y会发生]，因为[原因]'的格式。",
    tools:["ChatGPT","Claude","Perplexity"],
    links:[{name:"Perplexity",url:"https://perplexity.ai"},{name:"Google Scholar",url:"https://scholar.google.com"}]},

  {id:89, title:"分析研究论文", subtitle:"AI辅助批判性阅读", category:"science",
    description:"AI可以帮你批判性分析研究论文——识别方法论的优缺点、评估证据，并理解发现的更广泛意义。",
    steps:["找到并阅读研究论文","将关键部分粘贴给AI","请求批判性分析","用分析来指导你自己的工作"],
    prompt:"批判性分析这篇研究论文：\n\n[粘贴摘要和关键部分]\n\n请评估：\n1. 研究问题的清晰度和重要性\n2. 方法论的优点和缺点\n3. 样本量和选择的适当性\n4. 统计分析的有效性\n5. 结论是否由数据支持\n6. 潜在的偏见或利益冲突\n7. 这对该领域的贡献\n8. 仍未回答的问题",
    promptTip:"在请AI分析之前先自己阅读论文。用AI来发现你可能遗漏的东西，而不是替代你自己的批判性思维。",
    tools:["Claude","ChatGPT","Perplexity"],
    links:[{name:"Semantic Scholar",url:"https://www.semanticscholar.org"},{name:"Claude",url:"https://claude.ai"}]},

  {id:90, title:"创建科学插图", subtitle:"视觉化科学传播", category:"science",
    description:"科学插图帮助以视觉方式解释复杂概念。AI可以为你的报告、演示文稿和海报生成图表、信息图和插图。",
    steps:["描述要图解的科学概念","指定风格和详细程度","用AI图像工具生成","标注和注释插图"],
    prompt:"创建一个[概念：细胞结构/水循环/板块构造/DNA复制/电路图]的科学插图。风格：[教科书图表/信息图/简化卡通/详细插图]。包括：\n- 所有主要组件标注\n- 不同部分的颜色编码\n- 显示过程或流程的箭头\n- 清晰的教育性布局\n\n这是用于[学校报告/演示文稿/海报]的。",
    promptTip:"对于图表，AI的文字描述与Canva或draw.io配合效果很好。对于艺术性的科学插图，在Midjourney中使用'scientific illustration style'提示。",
    tools:["Midjourney","DALL-E","Canva","BioRender"],
    links:[{name:"BioRender",url:"https://www.biorender.com"},{name:"draw.io",url:"https://app.diagrams.net"}]},

  // ===== 趣味 (91-100+) =====
  {id:91, title:"规划旅行行程", subtitle:"AI驱动的旅行规划", category:"fun",
    description:"计划旅行？AI根据你的兴趣、预算和旅行风格创建详细的逐日行程。就像拥有一个了解每个目的地的私人旅行顾问。",
    steps:["分享你的目的地、日期、预算和兴趣","请AI创建逐日行程","根据偏好定制","保存餐厅和活动推荐"],
    prompt:"规划一次[天数]天的[目的地]旅行，[人数]人。预算：[预算水平：经济/中档/奢华]。兴趣：[兴趣：文化、美食、冒险、夜生活、历史、自然]。创建：\n- 逐日行程含时间安排\n- 必看景点和隐藏宝藏\n- 每餐餐厅推荐\n- 景点间交通提示\n- 每日预估费用\n- 行李建议\n- 当地习俗和小贴士",
    promptTip:"请问'游客通常错过的隐藏宝藏'和'不在旅游指南中的最佳当地美食'。旅行前务必核实营业时间和价格。",
    tools:["ChatGPT","Claude","Perplexity","Google Maps"],
    links:[{name:"Google Maps",url:"https://maps.google.com"},{name:"TripAdvisor",url:"https://www.tripadvisor.com"}]},

  {id:92, title:"用现有食材创造食谱", subtitle:"用手边的食材做饭", category:"fun",
    description:"打开冰箱，告诉AI你有什么食材，就能获得创意食谱。不再浪费食物或不知道做什么。AI还能适应饮食限制和烹饪水平。",
    steps:["列出你有的食材","提到任何饮食限制或偏好","请AI推荐食谱","跟随逐步烹饪说明"],
    prompt:"我有这些食材：[列出食材]。饮食限制：[无/素食/纯素/无麸质/等]。烹饪技能：[初学者/中级/高级]。可用设备：[烤箱/灶台/微波炉/等]。\n\n推荐3个我能用这些食材做的食谱。每个食谱：\n- 名称和描述\n- 准备和烹饪时间\n- 逐步说明\n- 让它更美味的小贴士\n- 搭配建议",
    promptTip:"诚实说明你的技能水平——AI会调整复杂度。时间紧时请求'20分钟以内的快速食谱'。保存你最喜欢的AI食谱！",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"ChatGPT",url:"https://chat.openai.com"},{name:"Allrecipes",url:"https://www.allrecipes.com"}]},

  {id:93, title:"生成健身计划", subtitle:"个性化健身方案", category:"fun",
    description:"AI根据你的体能水平、目标、可用设备和时间创建定制的健身计划。从居家训练到健身房计划，获得个性化的健身指导。",
    steps:["分享你的体能水平和目标","描述可用设备和时间","请AI创建训练计划","跟随计划并追踪进展"],
    prompt:"创建一个[时长：4周/8周]的训练计划，适合[初学者/中级/高级]，目标是[目标：增肌/减脂/提高耐力/增加柔韧性/综合健身]。可用设备：[无-仅体重/哑铃/完整健身房]。每次可用时间：[分钟]，每周[天数]天。\n\n每个训练日包括：\n- 运动名称及组数和次数\n- 休息时间\n- 正确姿势提示\n- 热身和放松\n- 渐进超负荷计划（如何增加难度）",
    promptTip:"从你认为需要的更简单开始。坚持比强度更重要。请AI提供'如果我还做不到[运动]的替代动作'。始终正确热身。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"ChatGPT",url:"https://chat.openai.com"},{name:"Nike Training Club",url:"https://www.nike.com/ntc-app"}]},

  {id:94, title:"创建个人预算", subtitle:"明智地管理你的钱", category:"fun",
    description:"理财素养越早培养越好。AI可以帮你创建个人预算、追踪支出、设定储蓄目标，并了解你的钱都花在了哪里。",
    steps:["列出所有收入来源","追踪一个月的支出","请AI创建预算计划","在电子表格或应用中设置追踪"],
    prompt:"帮我创建月度预算。我的情况：\n- 月收入：[金额]（来源：[零花钱/兼职/等]）\n- 固定支出：[列表：手机、订阅等]\n- 日常开销：[餐饮、交通、娱乐等]\n- 储蓄目标：[目标和金额]\n\n创建：\n1. 按类别的预算明细\n2. 50/30/20法则应用于我的收入\n3. 减少支出的建议\n4. 达到储蓄目标的计划\n5. 可以使用的电子表格模板",
    promptTip:"在做预算之前先追踪每一笔支出一个月——你会对钱的去向感到惊讶。使用50/30/20法则：50%必需品，30%想要的，20%储蓄。",
    tools:["ChatGPT","Claude","Google Sheets","Mint"],
    links:[{name:"Google Sheets",url:"https://sheets.google.com"},{name:"YNAB",url:"https://www.ynab.com"}]},

  {id:95, title:"设计梦想房间", subtitle:"AI室内设计", category:"fun",
    description:"想重新装修你的房间？AI可以根据你的风格、预算和房间尺寸建议布局、配色方案、家具摆放和装饰创意。",
    steps:["描述房间尺寸和当前设置","分享风格偏好和预算","请AI提供设计建议","用AI图像工具生成视觉概念"],
    prompt:"帮我重新设计我的[房间类型：卧室/书房/客厅]。尺寸：[大小]。想保留的现有家具：[列表]。我的风格：[极简/温馨/现代/波西米亚/游戏/美学]。预算：[金额]。\n\n建议：\n- 配色方案（墙色、点缀色）\n- 家具布局\n- 10个要买的装饰品（含估价）\n- 照明建议\n- 收纳方案\n- DIY项目\n\n让它感觉[氛围：温馨/高效/创意/放松]。",
    promptTip:"用AI图像生成器来可视化房间设计。Pinterest很适合找到具体产品。先从油漆/照明开始——它们以最少的成本产生最大的影响。",
    tools:["ChatGPT","Midjourney","Pinterest","IKEA"],
    links:[{name:"Pinterest",url:"https://www.pinterest.com"},{name:"IKEA",url:"https://www.ikea.com"}]},

  {id:96, title:"创作个性化故事", subtitle:"专为你定制的故事", category:"fun",
    description:"AI可以写出以你、你的朋友或任何角色为主角的个性化故事，任何类型都可以。互动小说、睡前故事、同人文或原创冒险——你的想象力引领一切。",
    steps:["描述角色和设定","选择类型和基调","请AI写故事","通过添加你的选择继续冒险"],
    prompt:"写一个[类型：冒险/悬疑/科幻/奇幻/爱情/喜剧]短篇故事。角色：\n- 主角：[姓名和描述]\n- 配角：[姓名和描述]\n\n设定：[何地何时]\n基调：[搞笑/严肃/悬疑/温暖]\n字数：约[字数]字\n\n包含生动的描写、对话和意想不到的转折。让它像翻页小说一样引人入胜。",
    promptTip:"对于互动小说，请AI'在每个部分结尾给我3个选择，根据我的选择继续'。这创造了一种'自己选择冒险'的体验！",
    tools:["ChatGPT","Claude","NovelAI"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:97, title:"生成知识问答游戏", subtitle:"和朋友一起玩", category:"fun",
    description:"AI可以为任何主题创建自定义知识问答游戏。非常适合游戏之夜、派对、学习小组或自我挑战。多种格式：知识竞赛、Jeopardy式或酒吧问答。",
    steps:["选择主题和难度级别","选择游戏格式","请AI生成问题和答案","和朋友或家人一起玩"],
    prompt:"创建一个知识问答游戏之夜，[数量]轮，每轮[数量]个问题。主题：\n第1轮：[主题：流行文化]\n第2轮：[主题：科学]\n第3轮：[主题：地理]\n第4轮：[主题：随机趣味知识]\n\n每个问题：\n- 问题文字\n- 4个选择题选项（一个正确）\n- 答案后的简短趣味解释\n\n难度：[简单/中等/困难/混合]。包含一个奖励轮！",
    promptTip:"混合难度级别：先简单建立信心，中间加难度，以有趣的奖励轮结束。通过描述图像让AI生成来添加图片轮。",
    tools:["ChatGPT","Claude","Kahoot"],
    links:[{name:"Kahoot",url:"https://kahoot.com"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:98, title:"策划活动和派对", subtitle:"完美的庆祝活动", category:"fun",
    description:"策划生日派对、学校活动或聚会？AI帮你组织一切——从主题和装饰到时间表、食物和活动。",
    steps:["定义活动类型、规模和预算","请AI创建全面计划","组织任务并分配","执行并享受！"],
    prompt:"帮我策划一个[活动类型：生日派对/毕业庆典/学校活动/游戏之夜]，[人数]人。预算：[金额]。日期：[日期]。场地：[家里/学校/户外/租赁场地]。\n\n创建完整计划包括：\n- 主题创意（3个选项）\n- 装饰清单含估价\n- 餐饮菜单\n- 活动和娱乐\n- 分钟级活动时间线\n- 音乐播放列表建议\n- 物资清单\n- 前一天vs当天的准备事项",
    promptTip:"至少提前2周开始策划。与帮忙的朋友创建共享清单。为户外活动请AI准备'下雨备用方案'。",
    tools:["ChatGPT","Claude","Canva","Spotify"],
    links:[{name:"Canva邀请函",url:"https://www.canva.com/invitations"},{name:"Spotify",url:"https://www.spotify.com"}]},

  {id:99, title:"创建愿景板", subtitle:"可视化你的目标", category:"fun",
    description:"愿景板帮助你可视化和实现目标。AI可以帮你清晰地定义目标、建议图像，并创建一个每天激励你的数字愿景板。",
    steps:["反思你来年的目标","请AI帮你定义具体可实现的目标","用AI生成视觉元素","组装你的愿景板"],
    prompt:"帮我创建一个[时间段：今年/未来5年/这学期]的愿景板。我的目标在以下领域：\n- 事业/学业：[目标]\n- 健康：[目标]\n- 个人成长：[目标]\n- 人际关系：[目标]\n- 娱乐/冒险：[目标]\n\n对每个目标：\n1. 使其具体且可衡量\n2. 建议一个激励性的图像或视觉来代表它\n3. 提供一句肯定语或名言\n4. 分解为月度里程碑",
    promptTip:"把愿景板放在你每天能看到的地方（手机壁纸、桌面、墙上）。每月审视和更新。力量在于每日可视化，而不仅仅是创建它。",
    tools:["ChatGPT","Midjourney","Canva","Pinterest"],
    links:[{name:"Canva",url:"https://www.canva.com"},{name:"Pinterest",url:"https://www.pinterest.com"}]},

  {id:100, title:"打造个人品牌", subtitle:"线上线下脱颖而出", category:"fun",
    description:"你的个人品牌就是世界看你的方式。AI可以帮你定义独特价值、创建一致的内容、建立网络存在感，并在人群中脱颖而出。",
    steps:["定义你的独特之处","创建品牌身份（视觉+语言）","建立网络存在感","持续创建内容"],
    prompt:"帮我打造个人品牌。关于我：\n- 姓名：[你的名字]\n- 年龄：[年龄]\n- 热情：[列出]\n- 技能：[列出]\n- 目标：[你想因什么而被认识]\n\n创建：\n1. 个人品牌声明（一句话）\n2. 3个内容支柱（应该发布的主题）\n3. Instagram/LinkedIn/TikTok简介\n4. 第一个月的内容创意（12篇帖子）\n5. 视觉风格指南（颜色、字体、照片风格）\n6. 如何真实地讲述我的故事\n7. 社交网络策略\n\n让它真实，不要假装或刻意。",
    promptTip:"真实胜过完美。发布你真正感兴趣的内容。保持一致——定期发布。与你领域的其他人互动。你的品牌应该感觉像你，只是被放大了。",
    tools:["ChatGPT","Claude","Canva","Linktree"],
    links:[{name:"Canva",url:"https://www.canva.com"},{name:"Linktree",url:"https://linktr.ee"},{name:"LinkedIn",url:"https://www.linkedin.com"}]},

  {id:109, title:"创建功能性电子游戏", subtitle:"用AI构建可玩的游戏——从平台跳跃到太空射击", category:"fun",
    description:"借助AI，你可以创建功能完整的电子游戏：2D平台跳跃、3D平台跳跃、roguelike、类银河恶魔城、跑跳闪躲攻击的动作游戏、大金刚克隆版、太空侵略者、青蛙过河，或你独创的游戏风格。一个可玩的原型可以在几分钟内准备好。细节和质量取决于你在打磨上投入的精力，但核心游戏循环组装起来出奇地快。",
    steps:["描述你想要的游戏类型（类型、机制、艺术风格）","请AI生成一个包含所有JavaScript、CSS和SVG图形的单一HTML文件","在浏览器中打开文件并测试","迭代：请AI添加功能、修复bug、改善图形或调整玩法","对于高级图形，请AI通过CDN使用Phaser或PixiJS","对于移动端支持，请AI添加虚拟摇杆和屏幕操作按钮"],
    prompt:"创建一个[类型：2D平台跳跃/太空射击/roguelike/无尽跑酷/益智]电子游戏，作为单个HTML文件，内嵌所有JavaScript和CSS。所有图形使用SVG（无外部图片）。游戏应包括：\n- 带[跑/跳/攻击/闪避]控制的玩家角色\n- 至少[3]个关卡或程序生成的内容\n- 有不同行为的敌人或障碍物\n- 得分和生命系统\n- 游戏结束和重新开始功能\n- 流畅的动画和响应式控制\n- 使用Web Audio API的音效\n\n艺术风格：[像素艺术/极简/多彩/复古/暗黑]。\n让控制手感紧凑且令人满意。\n\n高级选项：\n- 使用Phaser（通过CDN）获得内置物理、精灵管理和场景处理的专业游戏引擎\n- 或使用PixiJS（通过CDN）获得WebGL高性能2D渲染\n- 添加移动端支持：包含虚拟摇杆（左下角）和虚拟操作按钮（右下角），在触屏设备上访问时显示。屏幕控制应半透明且不遮挡游戏画面。",
    promptTip:"从简单开始——先让基本原型工作，然后一次添加一个功能。请AI'添加二段跳'、'创建Boss敌人'或'添加玩家冲刺时的粒子效果'。每次迭代都让游戏变得更好。保存为单个HTML文件，任何人只需打开文件就能玩。对于更精致的游戏，请AI通过CDN使用Phaser或PixiJS——这些提供真正的游戏引擎功能如物理、粒子系统和精灵表。对于移动玩家，请AI添加虚拟摇杆和屏幕按钮，这样游戏在手机和平板上也能玩。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:110, title:"创建ASCII艺术", subtitle:"用字符将文字变成视觉艺术", category:"fun",
    description:"ASCII艺术是仅使用文本字符（字母、数字和符号）创建图像、logo和插图的技艺。AI可以根据任何描述生成令人惊叹的ASCII艺术，从简单的涂鸦到极其精细的场景。这是为消息、代码注释、README文件增添视觉风格的有趣创意方式。",
    steps:["描述你想看到的ASCII艺术（动物、logo、场景、块字）","请AI用标准ASCII字符生成","指定大小：小（10-15行）、中（20-30行）或大（40+行）","请求变体或改进——尝试极简、详细或阴影等不同风格"],
    prompt:"创建[主题：猫/龙/山景/骷髅/块字'你好']的ASCII艺术。风格：[带阴影的精细/极简/卡通/写实]。大小：约[20]行高。仅使用标准ASCII字符（字母、数字、标点和符号）。让它视觉上引人注目且易于辨认。\n\n然后用完全不同的风格创建第二个版本进行对比。",
    promptTip:"为获得最佳效果，指定大小和风格。尝试'使用框线字符获得更整洁的外观'或'仅用点和空格获得半色调效果'。你也可以请AI将你描述的真实图像转换为ASCII艺术。非常适合代码注释、README文件和终端问候！",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:111, title:"创建ASCII艺术动画", subtitle:"让基于文本的艺术动起来", category:"fun",
    description:"将ASCII艺术提升到下一个层次——让它动起来！AI可以生成自包含HTML文件形式的ASCII动画——旋转地球、落雨、滚动风景、弹跳角色、黑客帝国式瀑布、烟花等。这些动画完全在浏览器中运行，令人着迷。",
    steps:["描述你想要的动画（什么在动、如何动、整体效果）","请AI创建使用JavaScript和等宽字体或canvas的单一HTML文件","在浏览器中打开HTML文件观看动画","迭代：请AI调整速度、添加颜色、更改场景或组合效果"],
    prompt:"创建一个ASCII艺术动画[动画：黑客帝国式绿色字符下落/旋转3D立方体/闪烁篝火/雨落城市景观/烟花爆炸/行走火柴人/海浪]，作为单个HTML文件。使用深色背景配[绿色/白色/彩色]字符。动画应：\n- 在浏览器中流畅运行\n- 使用等宽字体确保ASCII对齐\n- 包含至少[2-3]个视觉元素或层次\n- 感觉有氛围且令人着迷\n- 自动调整大小以填满浏览器窗口\n\n让它成为你想在第二个显示器上持续播放的东西。",
    promptTip:"尝试组合效果：'黑客帝国雨加偶尔的闪电'或'篝火场景配上升的火花和星空'。请求颜色渐变、速度控制或鼠标追踪等交互元素。这些效果作为屏幕保护程序非常惊艳！",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  // ===== 本地AI (108) =====
  {id:108, title:"运行你自己的本地AI（LLM）", subtitle:"在自己的电脑上运行AI模型——无需联网", category:"coding",
    description:"你不需要依赖云服务来使用AI。通过LM Studio，你可以直接在电脑上下载和运行强大的AI语言模型。它是免费的、私密的，且可以离线工作。这非常适合学习AI的底层工作原理、隐私敏感的项目，或者单纯享受在本地运行自己AI的快感。",
    steps:["访问lmstudio.ai下载适合你操作系统的LM Studio（Windows、Mac或Linux）。像普通应用一样安装。","打开LM Studio浏览模型库。从小型模型如'Llama 3.1 8B'或'Mistral 7B'开始——在大多数电脑上运行良好。","点击你选择的模型上的'Download'。下载可能需要几分钟，取决于模型大小（通常4-8 GB）。","下载完成后，进入'Chat'选项卡，选择你的模型，开始对话！功能和ChatGPT一样，但完全在你的电脑上运行。","探索设置来调整温度（创造性）、max tokens（响应长度）和系统提示。尝试不同的模型找到你最喜欢的。"],
    prompt:"我刚安装了LM Studio并下载了我的第一个本地LLM。帮我了解：我应该尝试哪些关键设置（温度、top-p、max tokens、系统提示）？给我每个设置的入门友好解释，并建议有趣的实验来尝试。",
    promptTip:"让你的本地AI写代码、创作故事、解释概念或帮助完成任务——全部完全离线且私密。尝试比较不同模型的回答。",
    tools:["LM Studio","Ollama"],
    links:[{name:"LM Studio",url:"https://lmstudio.ai"},{name:"Ollama（替代方案）",url:"https://ollama.ai"}]},

  // ===== 更多项目 =====
  {id:112, title:"提取视频的详细描述", subtitle:"获取任何视频内容的技术分析", category:"video",
    description:"AI可以观看视频并产出全面的技术描述——包括摄像角度、剪辑技术、转场、调色、音频设计、节奏、屏幕文字和内容结构。这对视频制作学生、无障碍工作、内容分析和通过研究现有视频学习影视技术非常有用。",
    steps:["将视频上传或分享给支持视频输入的AI（如Gemini或ChatGPT视觉功能）","请求详细的技术分析","指定想分析的方面：摄影、剪辑、音频、内容、节奏等","用分析来学习技术、创建无障碍描述或记录视频内容"],
    prompt:"详细分析这个视频并提供全面的技术描述，包括：\n- **视觉内容**：屏幕上出现什么，逐场景\n- **摄影**：摄像角度、运动、构图、镜头类型（广角、特写等）\n- **剪辑**：剪切时机、转场、节奏、韵律\n- **色彩和光线**：色彩调色板、调色风格、灯光设置\n- **音频**：音乐、音效、配音、对话、环境音\n- **文字和图形**：任何屏幕文字、标题、字幕、动画\n- **整体结构**：视频如何组织、叙事弧线、关键时刻\n\n要具体且专业——这个分析是给学习视频制作的人看的。",
    promptTip:"你可以将分析聚焦于特定方面：'只关注剪辑技术'或'详细描述调色'。对于长视频，请AI分析特定时间戳或片段。非常适合电影专业学生研究专业技术。",
    tools:["Gemini","ChatGPT","Claude"],
    links:[{name:"Gemini",url:"https://gemini.google.com"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:113, title:"提取图像的详细描述", subtitle:"获取任何图像的技术和创意分析", category:"art",
    description:"AI可以分析任何图像并产出丰富详细的描述——涵盖构图、色彩理论、光线、技术、风格、氛围和主题。这对艺术学生、摄影师、设计师和任何想理解图像为何有效的人都非常有价值。它也是创建无障碍alt-text描述的关键。",
    steps:["将图像上传到支持视觉的AI（ChatGPT、Claude、Gemini）","请求详细的技术和艺术分析","指定需要的分析类型：艺术评论、技术分析、无障碍描述或全部","用洞察来改进你自己的作品或创建适当的图像描述"],
    prompt:"全面详细地分析这张图像：\n\n**技术分析：**\n- 构图：三分法、引导线、对称、框架\n- 色彩：主导调色板、色彩和谐、对比度、饱和度\n- 光线：方向、质量（硬/软）、色温、阴影\n- 焦点和景深\n\n**艺术分析：**\n- 风格和类型（摄影、插画、数字艺术等）\n- 氛围和意境\n- 视觉叙事：这张图像讲述了什么故事？\n- 对艺术运动或风格的影响或引用\n\n**内容描述：**\n- 图像中一切可见内容的详细描述\n- 前景、中景、背景元素\n- 任何文字、符号或值得注意的细节\n\n以适合艺术或设计专业学生的专业级分析提供。",
    promptTip:"对于无障碍工作，具体请求：'写一段150字以内的屏幕阅读器alt-text描述'，然后'写一段给视觉障碍用户的更长描述'。对于摄影，请AI建议图像如何改进。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:114, title:"创建配色方案和调色板", subtitle:"为任何项目生成和谐的色彩组合", category:"art",
    description:"选择正确的颜色可以成就或毁掉一个设计。AI可以根据情绪、主题、品牌个性或参考图像生成完整的配色方案——附带十六进制代码、RGB值和使用指南。无论是设计网站、创作艺术、装修房间还是打造品牌，AI都能消除色彩理论中的猜测。",
    steps:["描述项目的情绪、主题或目的","请AI生成包含具体十六进制代码的调色板","要求使用指南：哪种颜色用于背景、文字、强调等","请求变体：更亮/更暗版本、互补调色板或无障碍替代方案"],
    prompt:"为[项目：现代科技网站/温馨咖啡店品牌/儿童绘本/健身应用/婚礼请柬]创建完整的配色方案。情绪应该是[情绪：专业可靠/温暖宜人/活泼有活力/优雅极简/大胆前卫]。\n\n提供：\n- **主色**：品牌主色（hex、RGB）\n- **辅色**：支持色（hex、RGB）\n- **强调色**：按钮、链接、高亮（hex、RGB）\n- **背景色**：主背景（hex、RGB）\n- **文字色**：确保可读性（hex、RGB）\n- **3个额外支持色**增加变化\n\n对每种颜色解释为什么适合这个项目以及在哪里使用。同时提供暗色模式版本。确保所有文字/背景组合符合WCAG AA无障碍对比度标准。",
    promptTip:"请求以特定事物为灵感的调色板：'受海上日落启发的色彩'或'感觉像东京雨天的调色板'。你也可以上传照片请AI从中提取调色板。尝试请求特定色彩和谐类型：类似色、互补色、三色组或分裂互补色。",
    tools:["ChatGPT","Claude","Gemini","Coolors"],
    links:[{name:"Coolors",url:"https://coolors.co"},{name:"Adobe Color",url:"https://color.adobe.com"}]},

  {id:115, title:"创建品牌套件和视觉指南", subtitle:"用AI构建完整的视觉识别系统", category:"business",
    description:"品牌套件是任何专业视觉识别的基础——它定义了logo使用、排版、配色方案、图像风格、语气和设计规则。AI可以帮你从零创建全面的品牌指南，节省数千元的设计公司费用。非常适合初创公司、学生项目、社团、个人品牌和小企业。",
    steps:["描述你的品牌：名称、使命、目标受众、个性和价值观","请AI生成包含所有视觉指南的完整品牌套件","审查和完善每个部分——调整颜色、字体和语气以匹配你的愿景","将指南导出为参考文档供任何为你品牌创建内容的人使用"],
    prompt:"为[品牌名称]创建全面的品牌套件和视觉识别指南，一个[描述：专注教育的科技初创公司/当地面包店/学生组织/个人创意作品集/健身教练业务]。\n\n目标受众：[受众]\n品牌个性：[特征：创新、友好、可靠/大胆、活力、年轻/优雅、精致、极简]\n\n包括：\n\n**1. 品牌概述**\n- 使命宣言建议\n- 品牌价值观（3-5个）\n- 品牌声音和语气指南附示例\n\n**2. 配色方案**\n- 主色、辅色和强调色含十六进制代码\n- 颜色使用规则（什么用在哪里）\n- 应避免的颜色\n\n**3. 排版**\n- 推荐的标题字体（含Google Fonts建议）\n- 推荐的正文字体\n- 字号和层次\n- 排版注意事项\n\n**4. Logo使用指南**\n- Logo放置规则\n- 最小尺寸要求\n- 留白要求\n- Logo的禁忌（拉伸、改色等）\n\n**5. 图像风格**\n- 摄影风格指南\n- 插画风格（如适用）\n- 图标风格建议\n- 图像注意事项\n\n**6. 社交媒体指南**\n- 帖子风格建议\n- 标签策略\n- 不同平台的语气\n\n让它足够详细，以便任何设计师或内容创作者都能一致地遵循。",
    promptTip:"要获得更完整的套件，后续请求：'现在按照这些指南创建示例社交媒体帖子'或'生成一页品牌摘要供我与合作者分享'。你也可以请AI将品牌套件创建为HTML页面，直观显示实际颜色和字体。",
    tools:["ChatGPT","Claude","Gemini","Canva"],
    links:[{name:"Canva品牌套件",url:"https://www.canva.com/brand"},{name:"Coolors",url:"https://coolors.co"}]},

  {id:116, title:"让AI扮演魔鬼代言人", subtitle:"通过让AI挑战来强化你的想法", category:"productivity",
    description:"使用AI最强大的方式之一是让它反驳你的想法。不是让AI一味同意你（AI倾向于这样做），而是指示它找出缺陷、挑战假设、戳穿论点中的漏洞。这让你的文章更有力、商业计划更健壮、决策更明智、思维更敏锐。就像随时有一个聪明的辩论伙伴。",
    steps:["将你的论点、文章、计划或想法分享给AI","请它扮演魔鬼代言人，找出每一个弱点","审视反驳论点——哪些是有效的？","通过应对最佳反对意见来加强你的原始作品","重复：请AI挑战改进后的版本进行另一轮"],
    prompt:"我要你扮演魔鬼代言人。这是我的[论点/文章/商业计划/想法/提案]：\n\n[粘贴你的作品]\n\n你的任务是：\n1. 找出每一个弱点、逻辑缺陷和无依据的声明\n2. 提出最强有力的反驳论点\n3. 识别我可能做出的错误假设\n4. 指出不同意的人会怎么说\n5. 建议具体的方法来加强我的论点\n\n严格但有建设性。不要手下留情——我要诚实、批判性的反馈，不是赞美。评论之后，用1-10的评分标准评估我的论点总体强度，并告诉我可以做出的最大改进。",
    promptTip:"这对论文、辩论准备、商业演示和任何需要压力测试思维的决策都非常有效。后续问：'现在帮我重写我的论点，解决你三个最强的反对意见'。你也可以请AI从特定视角进行论证：'从保守派/自由派/怀疑论者/投资者/科学家的角度反驳这个'。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  // ===== 新项目 (117-122) =====
  {id:117, title:"从数据创建交互式仪表板", subtitle:"将原始数据转化为专业的可视化仪表板", category:"business",
    description:"上传电子表格、输入数据或简单描述你拥有的信息——AI将生成一个完全交互式的仪表板，包含专业图表和统计数据。从销售报告到项目指标，AI可以将任何数据集转化为视觉上引人注目的交互式展示。附加功能：请求添加场景选择器，以便在不同数据视图之间切换，即时查看变化的影响。",
    steps:["准备数据：上传文件（Excel、CSV），粘贴表格，或描述想可视化的数据","请AI创建带图表和统计的单页HTML仪表板","指定重要指标：总计、平均值、趋势、比较、分布","请求交互元素：筛选器、日期范围、场景选择器","请求特定图表类型：柱状、折线、饼图、面积、散点或让AI选择最佳类型","迭代：请AI添加KPI、颜色编码、响应式布局或导出选项"],
    prompt:"创建一个交互式数据仪表板作为单个HTML文件，内嵌JavaScript和CSS。使用Chart.js（通过CDN）绘制图表。\n\n以下是我的数据：\n[粘贴数据/描述数据集/上传文件]\n\n仪表板应包括：\n- 带标题和日期的清晰专业布局\n- 顶部显示的关键绩效指标（KPI）大数字（总计、平均值、增长率）\n- 至少3种不同的最适合数据的图表类型（柱状、折线、饼图、面积等）\n- 适配桌面和移动端的响应式网格布局\n- 便于视觉扫描的颜色编码部分\n- 所有图表上显示精确数值的交互式提示框\n- 切换不同视图或时间段的筛选器或下拉菜单\n\n附加功能：添加'场景'选择器，可以在乐观、基线和悲观预测之间切换，查看对所有图表和KPI的影响。\n\n让它看起来像专业的商业智能工具。",
    promptTip:"数据越具体，仪表板越好。你可以直接粘贴表格、口头描述数据（'1月到12月的月销售额从1万到5万'）或上传CSV/Excel文件。请AI'添加暗色模式切换'或'导出图表为图片'。对于持续使用，请AI让数据可编辑，直接在仪表板中更新数字。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:118, title:"创建交互式场景模拟", subtitle:"构建带滑块、输入和实时结果的动态假设模型", category:"business",
    description:"AI可以创建完全交互式的场景模拟，你可以用滑块调整参数、输入自定义值或从预设场景中选择——并看到结果实时更新。非常适合财务建模、商业规划、资源分配、定价策略或任何需要回答'如果'问题的场景。每个场景可以包含自动化评论来解释你选择的含义。",
    steps:["描述你想建模的场景：变量是什么，结果是什么？","提供数据、范围和假设（或请AI建议合理默认值）","请AI创建带滑块、输入和场景预设的交互式HTML页面","指定要显示的结果：图表、统计摘要、建议、警告","请求自动化评论解释每个结果的含义","测试不同场景并迭代：添加更多变量、优化范围、改进界面"],
    prompt:"创建一个交互式场景模拟作为单个HTML文件，内嵌JavaScript和CSS。使用Chart.js（通过CDN）进行可视化。\n\n场景：[描述你的场景——如'包含价格、销量、成本和增长率变量的企业收入预测'/'股票、债券和房地产的投资组合配置'/'包含团队规模、范围和预算变量的项目时间线']\n\n模拟应包括：\n- 每个关键变量的滑块，带标注的最小/最大范围\n- 精确手动输入的数字字段\n- 至少3个预定义场景预设（如保守、适中、激进）作为可点击按钮\n- 滑块移动时实时更新的图表\n- 显示关键结果的结果面板（总计、ROI、时间线、风险等级等）\n- 结果下方的自动评论，解释当前场景的含义（如'以此增长率，你将在18个月内实现盈亏平衡'）\n- 颜色编码指标：绿色为有利结果，黄色为需注意，红色为风险\n\n附加功能：添加'自定义场景'按钮，允许保存和并排比较最多3个不同配置。\n\n让界面简洁、直观且专业。",
    promptTip:"这对商业规划、财务建模、资源分配、定价策略和教育模拟效果惊人。尝试：'添加敏感度分析显示哪个变量对结果影响最大'。你也可以请AI'添加蒙特卡洛模拟运行1000个随机场景'进行概率分析。提供的实际数据和约束条件越多，模拟越有用。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:119, title:"分析简历和筛选求职者", subtitle:"让AI基于你的标准预筛、评分和分类求职者", category:"business",
    description:"定义你的职位要求、评估标准和需要寻找的具体资质——然后让AI分析简历、预评分候选人并将其分类。AI可以筛选相关经验、技能、学历、证书、预警信号和文化匹配指标。它生成结构化比较，让你快速聚焦最有前途的候选人。重要提示：AI分析不能替代个人品格评估或适当的候选人评估——但它可以显著加速初始筛选过程并确保不会遗漏合格的候选人。",
    steps:["定义职位角色、所需技能、优选资质和淘汰标准","创建评分标准：什么最重要？技术技能、经验年限、学历、证书？","粘贴或上传要分析的简历/CV","请AI根据你的标准给每位候选人评分并排名","审查AI的分析和注释，标记需要仔细审阅的候选人","将结果作为起点——始终进行面对面访谈和评估"],
    prompt:"你是一位专业的HR筛选助手。我需要你分析以下职位的求职者：\n\n**职位：**[职位名称]\n**部门：**[部门]\n**关键要求：**\n- [要求1——如5年以上Python经验]\n- [要求2——如计算机科学或相关领域学士学位]\n- [要求3——如云平台（AWS/GCP/Azure）经验]\n\n**加分项：**\n- [优选技能1]\n- [优选技能2]\n\n**需注意的预警信号：**\n- [如超过1年的未解释就业空白]\n- [如长期没有职责晋升]\n\n以下是要分析的简历：\n[粘贴简历或上传文件]\n\n对每位候选人提供：\n1. **匹配分数**（0-100）基于满足要求的程度\n2. **等级分类**：A（强匹配）、B（良好匹配）、C（部分匹配）、D（弱匹配）\n3. **优势**：使该候选人脱颖而出的方面\n4. **顾虑**：空白、缺失技能或潜在问题\n5. **关键亮点**：最令人印象深刻的成就或资质\n6. **建议**：进入面试/待定/跳过\n\n最后提供按匹配分数排序的**排名比较表**。\n\n记住：这是筛选辅助工具，不是最终决定。始终进行面对面访谈。",
    promptTip:"为获得最佳结果，非常明确地说明你最看重什么——按重要性排列你的要求。你也可以请AI'技术技能权重40%，经验30%，学历20%，软技能10%'进行精确评分。尝试后续：'为每位候选人的薄弱环节生成定制面试问题'或'创建前3名候选人的并排比较'。大批量时，每次处理5-10份简历。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:120, title:"研究客户或潜在客户", subtitle:"生成关于潜在客户、客户或品牌的全面简报以赢得业务", category:"business",
    description:"让AI研究潜在客户、客户或品牌，生成专业简报帮你了解其业务、发现机会并为会议做准备。AI可以汇编公司历史、产品、市场地位、最新新闻、竞争对手、挑战和决策者的信息——为你提供赢得合同、定制提案和建立更强商业关系所需的情报。",
    steps:["提供公司或人的名称及已知详情","请AI研究并编制全面简报","指定需要的内容：公司概述、关键人物、最新新闻、痛点、竞争对手","请AI建议你的推介或会议的谈话要点和切入角度","要求一页摘要供通话或演示前审阅","定期更新简报：请AI查找最新新闻和动态"],
    prompt:"研究以下[公司/潜在客户/客户/品牌]并创建全面的商业情报简报：\n\n**目标：**[公司名称]\n**行业：**[如已知的行业]\n**背景：**[为什么在研究——如'准备销售会议'、'评估潜在合作伙伴'、'回应其RFP']\n\n创建详细简报涵盖：\n\n1. **公司概述**：做什么、规模、成立时间、总部、主要市场\n2. **产品和服务**：主要产品、定价模式、目标客户\n3. **市场地位**：与竞争对手的排名、市场份额、声誉\n4. **最新新闻和动态**：最新公告、产品发布、领导层变动、融资轮次\n5. **关键决策者**：CEO、相关VP/总监、背景和LinkedIn式简介\n6. **挑战和痛点**：基于行业和规模可能面临的问题\n7. **竞争对手**：前3-5个竞争对手及差异\n8. **我们的机会**：基于其挑战，我们的[产品/服务]在哪里可以增值？\n9. **谈话要点**：5个针对其具体情况的对话开场白\n10. **预警/风险**：需要谨慎的事项（财务问题、负面新闻、诉讼）\n\n格式化为专业的一页简报，可在会议前快速浏览。\n\n注意：请标记任何不确定的信息，区分已验证的事实和推断。",
    promptTip:"提供越多关于你自己业务和销售内容的背景，AI就能越好地定制机会和谈话要点。尝试后续：'现在起草一封给他们营销VP的个性化接触邮件'或'创建一个针对他们具体痛点的定制演示大纲'。你也可以问：'我们第一次会议中应该问什么问题来发现他们的真实需求？'对于持续客户，每季度更新简报。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"ChatGPT",url:"https://chat.openai.com"}]},

  {id:121, title:"适配你的个人学习风格", subtitle:"将任何主题定制为你最佳的学习方式", category:"learning",
    description:"我们每个人都有偏好和学习风格，让理解新概念变得更容易更舒适。有些人通过听和说学得更好（听觉型），有些通过做或移动（动觉型），有些通过看视觉表达或画图（视觉型），有些是空间型，还有些偏好阅读和写作。AI可以将任何主题或学习活动适配为最适合你的风格——将同样的材料转化为不同格式，让它自然地被你理解。",
    steps:["确定你偏好的学习风格（视觉、听觉、动觉、阅读/写作、空间）","告诉AI你想学的主题和偏好的风格","请AI以该格式呈现材料","请求替代格式来加强理解","结合多种风格获得更深入的理解"],
    prompt:"我想学习[主题]。我偏好的学习风格是[风格：视觉/听觉/动觉/阅读写作/空间]。\n\n请适配你的解释匹配我的风格：\n\n- 如果视觉：使用图表（文字描述）、图表、颜色编码、思维导图和意象\n- 如果听觉：写成对话、播客脚本或可以朗读的故事；使用节奏和重复\n- 如果动觉：设计动手活动、实验或我可以模拟的物理类比\n- 如果阅读/写作：提供详细的书面解释、列表、定义和笔记大纲\n- 如果空间：使用地图、空间类比、3D描述和关系定位\n\n解释之后，给我3个符合我风格的练习来强化概念。",
    promptTip:"不确定你的学习风格？问AI：'通过问我一系列关于偏好学习方式的问题来帮我发现我的学习风格'。你也可以用不同风格尝试同一主题，看哪个最有效。很多人是多模态的——用风格组合学习效果最好。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"VARK学习风格",url:"https://vark-learn.com"}]},

  {id:122, title:"创建学习主题的交互式模拟", subtitle:"构建你正在学习内容的可探索模型", category:"learning",
    description:"AI可以创建学习主题的交互式模拟和可视化表达——将抽象概念变成可探索的实践体验。想象操控物理模拟、观看化学反应展开、探索历史时间线或实时调整经济模型。这些模拟帮助你理解的不仅是发生了什么，还有为什么——通过让你改变变量并即时看到结果。",
    steps:["描述你想模拟的主题或概念","请AI创建交互式HTML模拟","指定想控制的变量（滑块、按钮、输入）","请求视觉表达（图表、动画、图解）","在浏览器中打开生成的HTML文件进行交互","通过请AI添加功能来修改和扩展模拟"],
    prompt:"创建一个自包含的交互式HTML模拟来帮助我理解[主题/概念]。\n\n模拟应该：\n- 是单个HTML文件，内嵌CSS和JavaScript\n- 包含交互控件（滑块、按钮或输入）来调整关键变量\n- 当我改变参数时显示实时视觉反馈\n- 显示清晰的标签解释每个控件的作用\n- 包含简短的解释部分描述被模拟的概念\n- 在有帮助的地方使用动画或动态图表\n\n主题：[具体主题——如'轨道力学和引力'、'供需曲线'、'DNA复制'、'电路']\n\n让它有教育性、视觉吸引力且无需说明就能直观使用。",
    promptTip:"这些模拟适用于几乎任何学科：物理（引力、波、光学）、化学（分子交互、pH）、生物（生态系统、细胞分裂）、经济学（市场模型）、数学（函数绘图、几何）、历史（交互式时间线）。请AI添加'挑战模式'，用你需要通过模拟来解决的问题。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"Claude",url:"https://claude.ai"},{name:"PhET Simulations",url:"https://phet.colorado.edu"}]},

  // ===== 音乐和音频（续） =====
  {id:123, title:"学习演奏一种乐器", subtitle:"AI驱动的个性化音乐学习计划", category:"music",
    description:"AI可以为你创建一个完整的、个性化的学习任何乐器的计划——从零基础到高级演奏者。它会评估你的可用时间，设定合理的期望，制定逐周课程，推荐设备，甚至生成有趣的知识来保持你的积极性。无论你是想弹出第一个吉他和弦还是精通钢琴，AI都能将令人望而生畏的音乐学习之旅变成一条清晰、有条理、可实现的道路。",
    steps:["告诉AI你想学什么乐器以及你目前的经验水平","说明你每周能投入多少小时练习","要求一个包含里程碑、课程和练习日历的完整学习计划","请求设备推荐、外部资源和趣味知识","使用高级提示词生成一个可追踪进度的独立HTML应用"],
    prompt:"我想学习演奏[乐器名称]。我的经验水平是[经验水平：完全零基础/以前弹过一点/多年后重新开始/想要提高的中级水平]。我每周大约可以投入[每周小时数：1-2/3-5/5-10/10+]小时练习。我的音乐目标是[目标：为了兴趣弹奏歌曲/加入乐队/现场演出/通过音乐考试/专业水平]。\n\n请创建一个全面的学习计划，包括：\n\n1. **[乐器名称]入门**：简要历史，工作原理，不同类型和种类，它的独特之处，以及人们喜爱演奏它的原因。\n\n2. **期望管理**：在学习的每个阶段我应该有怎样的合理期望。常见的挫折和瓶颈期，以及如何突破它们。解释进步并不总是线性的。\n\n3. **理解投入**：持续练习真正意味着什么，如何养成每日习惯，用心练习和随便弹弹的区别，以及成功者和放弃者之间的差异。\n\n4. **按投入程度的预期成果**：创建一个详细的表格，显示基于不同练习强度我可以期望达到的成就：\n\n| 每周小时数 | 1个月后 | 3个月后 | 6个月后 | 1年后 | 2年后 |\n|------------|---------|---------|---------|-------|-------|\n| 1-2小时    | ...     | ...     | ...     | ...   | ...   |\n| 3-5小时    | ...     | ...     | ...     | ...   | ...   |\n| 5-10小时   | ...     | ...     | ...     | ...   | ...   |\n| 10+小时    | ...     | ...     | ...     | ...   | ...   |\n\n为每个单元格填入具体、可量化的技能和里程碑。\n\n5. **详细学习计划**：前6个月的逐周计划，按月组织。每周包括：\n   - 具体的课程和练习\n   - 需要关注的技能（技巧、乐理、听力训练、曲目积累）\n   - 每个阶段要学习的歌曲或乐曲（从简单到中级）\n   - 推荐的练习环节结构（热身、技巧训练、新内容、复习、放松）\n   - 每月进度检查点，包含值得庆祝的具体成就\n\n6. **入门准备**：你需要的一切：\n   - 三个价位的乐器推荐（经济型、中端、优质型）\n   - 必备配件（附说明清单）\n   - 可选但有帮助的配件\n   - 练习空间设置（安静环境、照明、坐姿/姿势、温度）\n   - 有助于练习的应用和数字工具（节拍器、调音器、乐谱、伴奏音轨）\n\n7. **个人建议**：充分利用每次练习的技巧：\n   - 如何有效安排练习时间\n   - 一天中最佳练习时间以及如何保持坚持\n   - 如何避免身体受伤和劳损\n   - 心理建设：保持动力，应对挫折，庆祝小胜利\n   - 何时考虑找老师vs自学\n   - 当你只有10-15分钟时如何练习\n\n8. **推荐资源**：针对我这个水平的[乐器名称]学习者的具体书籍、YouTube频道、应用、在线课程、社区和网站。\n\n9. **其他见解**：关于学习音乐的常见误区，音乐如何影响大脑的科学知识，在他人面前演奏的技巧，如何找到合奏伙伴或乐团，以及新[乐器名称]学生应该知道的其他一切。\n\n10. **10个趣味知识**：分享10个关于[乐器名称]或其乐器家族的令人惊讶、有趣或鼓舞人心的趣味知识。\n\n用标题、要点和投入表格清晰地格式化输出。使内容实用、鼓舞人心，并对前方的旅程保持诚实。\n\n最后，以可下载内容的形式提供完整计划：\n- 在屏幕上显示完整计划\n- 提供可复制的Markdown版本\n- 提供可保存的HTML版本\n- 建议如何将其转换为Word和PDF",
    promptTip:"将[乐器名称]替换为任何乐器：吉他、钢琴、小提琴、鼓、尤克里里、贝斯、长笛、萨克斯、小号、大提琴等。具体说明你的目标——'我想弹篝火旁的歌曲'和'我想演奏古典独奏会'会产生截然不同的计划。你还可以添加限制条件，如'我住在公寓里所以噪音是个问题'或'我的设备预算是200美元'。",
    prompt2Label:"示例：完整的吉他学习计划",
    prompt2:"我想学习弹奏原声吉他。我是一个完全的零基础初学者——我从未弹过任何弦乐器。我每周大约可以投入3-5小时练习（每天约30-45分钟，每周5-6天）。我的目标是为了兴趣弹奏歌曲——篝火旁的歌曲、可以边弹边唱的流行歌曲，最终还想学指弹。\n\n请创建一个全面的学习计划，包括：\n\n1. **吉他入门**：原声吉他简史，它如何发声，原声吉他、古典吉他和电吉他的区别，吉他各部分（琴头、调音旋钮、弦枕、指板、品丝、琴体、音孔、琴桥、下弦枕、琴弦），以及吉他为什么是世界上最受欢迎的乐器之一。\n\n2. **期望管理**：一个完全的初学者应该有怎样的合理期望。诚实地讲述手指疼痛（茧需要2-4周形成）、换和弦的挫折感、\"难听的声音\"阶段，以及弹奏完整歌曲的典型时间线。解释每个人都会经历这些，而且情况会显著好转。\n\n3. **理解投入**：每天30分钟的专注练习如何胜过周末3小时的随便弹弹。漫无目的地弹和刻意练习的区别。如何养成习惯：固定时间、固定地点、吉他随时可取。是什么让吉他学习者放弃（通常在第3-6周）以及如何坚持下去。\n\n4. **按投入程度的预期成果**：\n\n| 每周小时数 | 1个月后 | 3个月后 | 6个月后 | 1年后 | 2年后 |\n|------------|---------|---------|---------|-------|-------|\n| 1-2小时 | 基础开放和弦（Em、Am），简单扫弦 | 4-5个和弦，1-2首简单歌曲 | 8+个和弦，3-5首歌，基本节奏 | 开始学大横按和弦，10+首歌 | 自信的节奏吉他手 |\n| 3-5小时 | Em、Am、G、C、D和弦，基本扫弦模式 | 流畅换和弦，3-4首歌，基础指弹 | 完整歌曲加演唱，大横按入门，基础乐理 | 大横按和弦熟练，指弹模式，20+首歌 | 中级水平，部分主音吉他 |\n| 5-10小时 | 所有基础开放和弦，2-3种扫弦模式，第一首歌 | 流畅的和弦转换，6-8首歌，基础乐理，简单指弹 | 大横按和弦，变调夹使用，10+首歌，开始即兴 | 主音吉他基础，多种风格，可以为他人演奏 | 中高级，复杂指弹，独奏 |\n| 10+小时 | 开放和弦加部分大横按，多种扫弦模式，2-3首歌 | 自信的和弦弹奏，基础音阶，10+首歌，乐理基础 | 中级水平，即兴演奏，多种曲风，可以表演 | 高级技巧，乐理精通，歌曲创作 | 接近高级水平，复杂乐曲，自信的表演者 |\n\n5. **详细学习计划**（逐周，6个月）：\n\n**第1个月——基础：**\n- 第1周：吉他结构认识（琴头、调音旋钮、弦枕、品丝、琴体、音孔、琴桥、琴弦），正确持琴姿势，使用夹式调音器或GuitarTuna应用调音，右手在空弦上的扫弦动作，手指放置基础\n- 第2周：第一批和弦——Em和Am。练习和弦指型，干净的按弦，Em和Am之间的切换。简单下行扫弦模式（每小节4拍）\n- 第3周：加入G和弦。Em到Am到G的转换。4/4拍子入门。下-下-上扫弦模式。小歌曲练习：\"Horse With No Name\"（Em-D6/9，只有2个指型）\n- 第4周：加入C和弦。练习全部4个和弦：Em、Am、G、C。月度检查点：以60 BPM的速度流畅弹奏Em-Am-G-C进行\n- 歌曲：\"Horse With No Name\"（America）、\"Leaving on a Jet Plane\"（John Denver）——简化版\n\n**第2个月——建立信心：**\n- 第5周：加入D和弦。C-G-D转换。新扫弦模式：D-DU-UDU。第一首完整歌曲：\"Knockin' on Heaven's Door\"（G-D-Am/G-D-C）\n- 第6周：学习阅读和弦图和歌曲谱。练习\"Let It Be\"（C-G-Am-Fmaj7）。手指灵活性练习（蜘蛛爬行、1-2-3-4半音阶练习）\n- 第7周：加入E和弦。音乐调性的概念。在已学的全部7个和弦之间转换。歌曲：\"Wish You Were Here\"前奏\n- 第8周：复习月。配合节拍器完整弹奏3-4首歌。月度检查点：不停顿地从头到尾弹奏2首歌\n- 歌曲：\"Knockin' on Heaven's Door\"（Bob Dylan）、\"Let It Be\"（Beatles）、\"Wish You Were Here\"（Pink Floyd）\n\n**第3个月——拓展技能：**\n- 第9周：指弹入门——拇指-食指-中指模式（Travis picking基础）。用Am、C、G练习指弹\n- 第10周：加入A和弦和Dm和弦。小调vs大调的音色。歌曲：简化版\"Dust in the Wind\"指弹\n- 第11周：变调夹入门——原理和用途。使用变调夹在新调中弹奏歌曲。用变调夹匹配你的声域\n- 第12周：基础乐理入门：第5-6弦上的音名，和弦名称的含义，数字体系（I-IV-V）。月度检查点：指弹一首歌，自信地扫弦弹奏两首歌\n- 歌曲：\"Dust in the Wind\"（Kansas）——简化版、\"Hallelujah\"（Leonard Cohen）——使用变调夹\n\n**第4个月——中级基础：**\n- 第13周：可怕的F和弦——从Fmaj7作为过渡开始，然后是小横按F。每天大横按和弦练习（2分钟）\n- 第14周：强力和弦（E5、A5、D5）。闷音技巧。用强力和弦弹一首摇滚歌曲\n- 第15周：八分音符扫弦模式。切分音。歌曲：\"Wonderwall\"配合正确的扫弦模式\n- 第16周：建立个人歌单，8-10首歌。月度检查点：为朋友演奏你最拿手的3首歌，或录下自己的演奏\n- 歌曲：\"Wonderwall\"（Oasis）、\"Good Riddance\"（Green Day）、\"Have You Ever Seen the Rain\"（CCR）\n\n**第5个月——风格与表现力：**\n- 第17周：锤弦和勾弦技巧。用装饰音修饰和弦\n- 第18周：小调五声音阶——第一把位。在12小节蓝调伴奏音轨上进行基础即兴\n- 第19周：不同扫弦风格的多样性：民谣、流行、雷鬼、乡村模式。将不同风格应用到已学歌曲\n- 第20周：边弹边唱。从简单扫弦加人声开始。月度检查点：边弹边唱2首歌，基础蓝调独奏\n- 歌曲：\"Redemption Song\"（Bob Marley）、\"Hey Joe\"前奏（Jimi Hendrix）\n\n**第6个月——融会贯通：**\n- 第21周：大横按和弦精通——完整F、Bm、B。在歌曲中进行开放和弦到大横按的转换\n- 第22周：高级指弹——琶音、交替低音。歌曲：\"Blackbird\"（Beatles）或\"Stairway to Heaven\"前奏\n- 第23周：建立终极演出歌单。练习表演：从错误中恢复、歌曲过渡、舞台表现力\n- 第24周：录制你最好的5首歌。与第1周对比。庆祝你的进步！规划下一个6个月。月度检查点：为家人或朋友进行15分钟的迷你音乐会（5首歌）\n- 歌曲：\"Blackbird\"（Beatles）、\"Stairway to Heaven\"前奏（Led Zeppelin）\n\n*练习环节结构（30分钟）：*\n- 3分钟：热身（手指拉伸、半音阶练习）\n- 5分钟：技巧训练（和弦转换、音阶练习或指弹模式）\n- 10分钟：新内容（学习新歌曲片段、新和弦或新技巧）\n- 10分钟：曲目复习（弹奏已学歌曲，专注薄弱环节）\n- 2分钟：放松（弹一些你喜欢的，自由弹奏）\n\n6. **入门准备**：\n- **吉他**（经济型约80-120美元）：Yamaha FG800、Fender FA-15——（中端约200-400美元）：Taylor Academy 10、Yamaha FG830——（优质约500美元以上）：Taylor 114ce、Martin D-15M\n- **必备配件**：夹式调音器（10-15美元）、备用琴弦一套（5-8美元）、吉他拨片——各种厚度混合装（3-5美元）、吉他背带（8-15美元）、变调夹（8-12美元）\n- **实用附件**：吉他支架或墙挂钩（12-25美元）、节拍器应用（免费）、手指训练器/握力器（8-12美元）、乐谱架（15-30美元）、无扶手的舒适椅子\n- **练习空间**：不会被打扰的安静房间，良好照明，无扶手的椅子，吉他放在支架上（不要放在琴盒里——看得见的吉他=更多练习）\n- **应用**：GuitarTuna（免费调音器）、Justin Guitar应用（免费课程）、Ultimate Guitar（和弦谱）、Songsterr（交互式吉他谱）、Metronome Beats（免费）\n\n7. **个人建议**：\n- 把吉他从琴盒里拿出来，放在支架上，放在你待得最多的房间里。看到它，你就会拿起它\n- 每天在固定时间练习——将其与现有习惯绑定（早咖啡后、晚饭后）\n- 每月录制自己的演奏。你不会注意到每天的进步，但月度录音会显示巨大的提升\n- 当手指疼痛时，再多练5分钟就停下。持续短时间接触能更快形成茧\n- 学你真正喜欢的歌。动力永远胜过方法\n- 跟着录音或伴奏音轨一起弹——更有趣且能训练你的节奏感\n- 不要拿你的第30天和别人的第3年比。和你自己的第1天比\n- 考虑至少在第一个月找一位老师，以避免姿势和技巧上的坏习惯\n- 加入Reddit的r/guitar或当地吉他社群——社区让你保持自律\n- 当你遇到瓶颈期（每个人大约在第2-3个月都会），学一种完全不同风格的歌来重燃热情\n\n8. **推荐资源**：\n- **YouTube**：Justin Guitar（最佳免费课程）、Marty Music、Andy Guitar\n- **应用**：Yousician（互动式）、Fender Play（结构化课程）、Justin Guitar应用\n- **书籍**：\"Hal Leonard Guitar Method\"（结构化教程）、\"Guitar Aerobics\"（每日练习）\n- **网站**：Ultimate-Guitar.com（吉他谱和和弦）、Songsterr.com（交互式吉他谱）\n- **社区**：r/guitarlessons、r/beginnerguitar、当地开放麦之夜\n\n9. **其他见解**：\n- 误区：\"你需要天赋。\"现实：吉他95%靠练习，5%靠天资。几乎任何人都能学会\n- 误区：\"你需要先学会读五线谱。\"现实：大多数吉他手使用吉他谱和和弦图——逐步学习乐理\n- 演奏音乐降低皮质醇（压力荷尔蒙）并增加多巴胺——它真的能让你更快乐\n- 你只需要4个和弦（G、Em、C、D）就能弹奏数百首流行歌曲\n- 学吉他能提高手眼协调能力、记忆力，甚至数学思维\n- 找合奏伙伴的最佳时机：3-4个月后，当你能稳定弹奏基本和弦进行时\n\n10. **关于吉他的10个趣味知识**：\n1. 吉他的祖先可追溯到4000多年前的古巴比伦\n2. 世界上最大的可演奏吉他长43英尺——由德克萨斯州的学生建造\n3. Jimi Hendrix是左撇子，但他把右手吉他翻转过来弹——他重新排列了琴弦，使低音E弦仍在上方\n4. 有史以来最贵的吉他是Kurt Cobain的\"MTV Unplugged\" Martin D-18E，2020年以600万美元售出\n5. 尼龙弦（古典吉他）实际上由碳氟化合物或尼龙制成，而\"钢弦\"通常是青铜缠绕的\n6. 吉他是世界上最受欢迎的乐器——估计有5000万人在弹奏\n7. 大约需要100小时的弹奏才能在指尖形成永久的茧\n8. 吉他上的品丝使用2的12次方根（≈1.05946）来放置——纯数学创造了音乐和谐\n9. 弹吉他同时使用大脑的两个半球——很少有活动能做到这一点\n10. \"guitar\"一词来自西班牙语\"guitarra\"，而它源自希腊语\"kithara\"——一种古老的弦乐器\n\n清晰地使用标题、要点和投入表格来格式化所有内容。使其实用、鼓舞人心且诚实。",
    prompt3Label:"高级：交互式学习规划器（HTML应用）",
    prompt3:"创建一个完整的、自包含的HTML文件（单个文件，内嵌所有CSS和JavaScript），作为\"音乐学习规划器\"应用。该应用应该美观、专业且功能完整。\n\n规划的乐器是：[乐器名称]\n用户的经验水平是：[经验水平：完全零基础/有一些经验/中级]\n用户可以练习：[每周小时数：3-5]小时每周\n\nHTML应用必须有三个主要部分，通过顶部的标签导航栏访问：\n\n**标签1：我的资料和设置**\n- 可编辑字段：学生姓名、乐器、经验水平（下拉菜单）、每周小时数（滑块：1-20）、开始日期（日期选择器）、音乐目标（文本输入）\n- 练习日历，用户可以勾选每周哪几天练习，带有每周小时计算器\n- 进度部分，带滑块（0-100%）：技巧、乐理、听力训练、曲目积累、表演自信\n- \"更新计划\"按钮，根据这些设置调整标签2的内容\n- 所有输入应预填[乐器名称]的合理默认值\n\n**标签2：我的学习计划**\n- 根据标签1的设置生成\n- 按月组织为可折叠部分（第1-6个月）\n- 每月包含每周课程：\n  - 要学习的技能\n  - 练习和训练\n  - 要练习的歌曲/乐曲\n  - 乐理概念\n  - 要达成的里程碑\n- 投入/成果表格（每周小时数vs时间线），显示预期成就\n- 准备清单部分：乐器、配件、空间、应用\n- 技巧和建议部分\n- 关于该乐器的10个趣味知识\n- **标签2顶部的操作按钮：**\n  - \"打印计划\"——打开浏览器打印对话框，带有打印优化的CSS\n  - \"导出为Markdown\"——下载计划为.md文件\n  - \"导出为Word\"——下载计划为.docx文件（使用基本HTML到Word转换，通过Blob生成Word兼容HTML）\n  - \"导出为PDF\"——使用html2canvas（CDN：https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js）和jsPDF（CDN：https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js）下载计划为PDF\n\n**标签3：仪表盘和进度**\n- 使用Chart.js（CDN：https://cdn.jsdelivr.net/npm/chart.js）的可视化仪表盘\n- 包含的图表：\n  - 雷达图：显示技能水平（来自标签1的进度滑块）\n  - 折线图：基于每周小时投入显示24个月的预计进度\n  - 柱状图：显示练习小时目标vs实际（每周视图）\n  - 环形图：显示时间分配建议（技巧、乐理、曲目积累、听力训练）\n- 进度摘要：开始以来的天数、总估计练习小时数、当前水平估计\n- 激励部分：下一个里程碑、连续天数计数器、鼓励消息\n- 当标签1数据变化时所有图表动态更新\n\n**导入/导出系统：**\n- \"导出数据\"按钮（在页眉或页脚中），将所有用户偏好、进度滑块、日历选择和设置保存为扩展名为`.cemimusic`的可下载文件\n- .cemimusic文件格式为JSON，结构如下：\n  ```json\n  {\n    \"version\": \"1.0\",\n    \"app\": \"CemiMusicPlanner\",\n    \"exportDate\": \"ISO-date-string\",\n    \"profile\": { name, instrument, level, hoursPerWeek, startDate, goal },\n    \"progress\": { technique, theory, earTraining, repertoire, confidence },\n    \"calendar\": { practiceDays: [bool x 7], practiceLog: {} },\n    \"customNotes\": \"\"\n  }\n  ```\n- \"导入数据\"按钮，加载.cemimusic文件并恢复所有设置，更新所有三个标签\n- 导入时包含验证以确保文件格式正确\n\n**设计：**\n- 现代、简洁的设计，带有音乐主题配色方案\n- 响应式布局，适用于桌面和移动设备\n- 流畅的标签切换动画\n- 专业排版（通过CDN使用Google Fonts）\n- 细微的音乐主题装饰元素（音符、五线谱等，通过CSS或SVG实现）\n- 深色/浅色模式切换\n\n使应用功能完全正常——所有按钮、导出、导入、图表和计算都应该能工作。文件应该完全自包含（单个HTML文件，所有依赖通过CDN加载）。",
    prompt4Label:"试一试：吉他学习规划器（预填版）",
    prompt4:"创建一个完整的、自包含的HTML文件（单个文件，内嵌所有CSS和JavaScript），作为\"吉他学习规划器\"应用。该应用应该美观、专业且功能完整。\n\n乐器是：原声吉他\n用户的经验水平是：完全零基础\n用户可以练习：每周4小时（每天约35分钟，每周6天）\n\nHTML应用必须有三个主要部分，通过顶部的标签导航栏访问：\n\n**标签1：我的资料和设置**\n- 预填字段：\n  - 学生姓名：\"吉他学员\"\n  - 乐器：\"原声吉他\"\n  - 经验水平：\"完全零基础\"（下拉菜单选项：完全零基础、有一些经验、中级、高级）\n  - 每周小时数：4（滑块：1-20）\n  - 开始日期：今天的日期（日期选择器）\n  - 音乐目标：\"在篝火旁弹唱歌曲，学习流行原声歌曲，最终学会指弹\"\n- 练习日历预设：周一到周六勾选，周日休息。每周小时显示4.0\n- 进度滑块预设为：技巧0%、乐理0%、听力训练0%、曲目积累0%、表演自信0%（初学者起点）\n- \"更新计划\"按钮，当设置更改时调整标签2的内容\n\n**标签2：我的学习计划**\n为原声吉他零基础、每周4小时预生成：\n\n- 按月组织为可折叠部分（第1-6个月）\n- 每月包含每周课程：\n  - 要学习的技能（从基础和弦到大横按、指弹）\n  - 练习和训练（扫弦模式、手指灵活性、乐理）\n  - 要练习的歌曲/乐曲（从简单两和弦歌曲到经典摇滚民谣）\n  - 乐理概念（和弦构成、调性、数字体系）\n  - 要达成的里程碑（月度检查点）\n- 练习环节结构（35分钟）：热身、技巧训练、新内容、曲目复习、自由弹奏\n- 投入/成果表格（每周小时数vs时间线），显示1个月、3个月、6个月、1年、2年后的预期成就\n- 准备清单部分：\n  - 吉他选择（经济型、中端、优质）：Yamaha FG800、Taylor Academy 10、Martin D-15M等\n  - 必备配件：调音器、琴弦、拨片、背带、变调夹\n  - 实用附件：支架、节拍器、手指训练器、乐谱架\n  - 练习空间设置\n  - 推荐应用：GuitarTuna、Justin Guitar、Ultimate Guitar、Songsterr\n- 关于吉他的10个趣味知识\n- **标签2顶部的操作按钮：**\n  - \"打印计划\"——打开浏览器打印对话框，带有打印优化CSS\n  - \"导出为Markdown\"——下载为guitar-learning-plan.md\n  - \"导出为Word\"——下载为guitar-learning-plan.docx\n  - \"导出为PDF\"——使用html2canvas + jsPDF（通过CDN）下载为guitar-learning-plan.pdf\n\n**标签3：仪表盘和进度**\n- 使用Chart.js（CDN：https://cdn.jsdelivr.net/npm/chart.js）的图表：\n  - 雷达图：技能水平（技巧0%、乐理0%、听力训练0%、曲目积累0%、自信0%）\n  - 折线图：基于每周4小时的24个月预计进度（平滑曲线，显示前期快速提升，然后逐步改善）\n  - 柱状图：每周练习目标（4小时）vs实际小时数（起始为0，用户可记录）\n  - 环形图：推荐时间分配——技巧25%、曲目积累35%、乐理15%、听力训练15%、自由弹奏10%\n- 进度摘要：开始以来0天，总计0小时，水平：完全零基础\n- 下一个里程碑：\"学会你的第一个和弦（Em）——第1周\"\n- 激励消息：\"每一位吉他手都曾站在你现在的起点。拿起你的吉他，弹出你的第一个音符吧！\"\n\n**导入/导出系统：**\n- \"导出数据\"按钮，将所有设置保存为`.cemimusic`文件（JSON格式）：\n  ```json\n  {\n    \"version\": \"1.0\",\n    \"app\": \"CemiMusicPlanner\",\n    \"exportDate\": \"2025-01-15T10:00:00Z\",\n    \"profile\": {\n      \"name\": \"Guitar Student\",\n      \"instrument\": \"Acoustic Guitar\",\n      \"level\": \"Complete Beginner\",\n      \"hoursPerWeek\": 4,\n      \"startDate\": \"2025-01-15\",\n      \"goal\": \"Play songs around a campfire, learn popular acoustic songs, eventually fingerpick\"\n    },\n    \"progress\": {\n      \"technique\": 0,\n      \"theory\": 0,\n      \"earTraining\": 0,\n      \"repertoire\": 0,\n      \"confidence\": 0\n    },\n    \"calendar\": {\n      \"practiceDays\": [true, true, true, true, true, true, false],\n      \"practiceLog\": {}\n    },\n    \"customNotes\": \"\"\n  }\n  ```\n- \"导入数据\"按钮，加载.cemimusic文件并恢复所有三个标签的设置\n- 导入时验证文件格式，如果无效则显示友好的错误提示\n\n**设计：**\n- 温暖的原声配色方案：木色调（#8B6914、#D4A843）、奶油色（#FFF8E7）、深棕色（#3E2723）、琥珀色点缀（#FF8F00）\n- 响应式布局——适用于桌面和移动设备\n- 流畅的标签切换\n- Google Fonts：\"Inter\"用于正文，\"Playfair Display\"用于标题\n- 细微的吉他主题SVG装饰（页眉中的吉他轮廓，音符作为分隔线）\n- 深色/浅色模式切换（默认：浅色，暖色调主题）\n\n使一切功能完全正常。所有导出、导入、图表、计算和按钮都必须能工作。单个自包含HTML文件，所有依赖通过CDN加载。",
    tools:["ChatGPT","Claude","Gemini"],
    links:[{name:"Justin Guitar",url:"https://www.justinguitar.com"},{name:"Ultimate Guitar",url:"https://www.ultimate-guitar.com"},{name:"Yousician",url:"https://yousician.com"},{name:"收听我们的AI增强艺术家",url:"https://maimusic.org"}]}
];
