var FUN_FACTS = [
    // AI History
    "The term 'Artificial Intelligence' was coined in 1956 at a summer workshop at Dartmouth College, making AI as a field nearly 70 years old.",
    "Alan Turing proposed the famous Turing Test in 1950, suggesting that if a machine can fool a human into thinking it is also human, it can be considered intelligent.",
    "The first AI program, called the Logic Theorist, was created in 1956 and could prove mathematical theorems on its own.",
    "In 1966, MIT built ELIZA, one of the first chatbots, which mimicked a psychotherapist so convincingly that some users believed they were talking to a real person.",
    "AI research went through two major 'AI winters' in the 1970s and 1980s, where funding and interest dried up because early promises were too ambitious.",
    "The term 'machine learning' was first used in 1959 by Arthur Samuel, who built a program that learned to play checkers better than he could.",

    // How AI Models Work
    "Large language models like GPT-4 have hundreds of billions of parameters, which are tiny numerical dials the model adjusts during training to learn patterns.",
    "Training a single large AI model can cost tens of millions of dollars in electricity and computing power alone.",
    "AI models read text as 'tokens,' which are chunks of words. The word 'hamburger' might be split into 'ham,' 'bur,' and 'ger' as three separate tokens.",
    "A neural network is loosely inspired by the human brain and consists of layers of interconnected nodes that pass signals to each other.",
    "During training, an AI model can look at billions of sentences from the internet, books, and articles to learn how language works.",
    "AI doesn't actually 'understand' language the way humans do. It predicts the most likely next word based on patterns it learned during training.",
    "Reinforcement learning trains AI by giving it rewards for good actions and penalties for bad ones, similar to how you might train a pet.",

    // AI in Daily Life
    "Every time Netflix suggests a show you might like, that recommendation is powered by AI algorithms analyzing your viewing history.",
    "The autocomplete suggestions on your phone keyboard are generated by a small AI model that learns your personal typing habits over time.",
    "Spam filters in your email use AI to block roughly 85 billion spam messages every single day worldwide.",
    "When you unlock your phone with your face, an AI model is mapping and recognizing over 30,000 invisible dots projected onto your face.",
    "Social media feeds are curated by AI algorithms that decide which posts you see first based on what you are most likely to engage with.",
    "Virtual assistants like Siri, Alexa, and Google Assistant process your voice using AI that converts sound waves into text and then interprets the meaning.",
    "Many online stores use AI chatbots for customer service, and studies show that about 40% of people cannot tell they are chatting with a bot.",

    // AI Art and Creativity
    "In 2018, an AI-generated portrait called 'Edmond de Belamy' sold at Christie's auction house for $432,500, shocking the art world.",
    "AI art generators like DALL-E and Midjourney can create a detailed, original image from a text description in just a few seconds.",
    "Some AI models can generate art in the style of famous painters like Van Gogh or Picasso without ever having 'seen' an actual painting.",
    "AI-generated art has sparked huge debates about copyright, since no human physically created the artwork yet a human wrote the prompt.",
    "There are AI tools that can turn a rough doodle or sketch into a polished, photorealistic image in seconds.",

    // AI in Gaming
    "In 1997, IBM's Deep Blue became the first computer to beat a reigning world chess champion, Garry Kasparov, in a full match.",
    "DeepMind's AlphaGo defeated the world champion at Go in 2016, a game so complex it has more possible board positions than atoms in the universe.",
    "AI bots have beaten professional human players in Dota 2, a game that requires long-term strategy, teamwork, and real-time decision making.",
    "Many video game enemies and NPCs use AI behavior trees to decide how to react to a player's actions in real time.",
    "AI is used to generate entire game levels procedurally, meaning no two playthroughs are exactly the same in games like Minecraft and No Man's Sky.",
    "OpenAI Five, the AI that played Dota 2, practiced the equivalent of 45,000 years of gameplay in just ten months of training.",

    // AI in Medicine and Science
    "AI can now detect certain cancers from medical scans with accuracy equal to or better than experienced human doctors.",
    "DeepMind's AlphaFold solved a 50-year-old biology problem by predicting the 3D shapes of nearly every known protein, revolutionizing drug discovery.",
    "AI systems can analyze a retinal eye scan and detect early signs of diabetes, sometimes before a patient shows any other symptoms.",
    "Researchers use AI to discover new antibiotics by having models scan millions of chemical compounds for bacteria-killing properties.",
    "AI helped scientists at CERN analyze data from particle collisions, contributing to the discovery of the Higgs boson particle.",
    "During the COVID-19 pandemic, AI was used to accelerate vaccine development by predicting which protein structures would trigger the best immune response.",
    "AI-powered robotic surgery systems can make incisions with sub-millimeter precision, far steadier than a human hand.",

    // AI Language Abilities
    "Modern AI translation models can translate between over 200 languages, including many that have very few digital resources available.",
    "AI can now generate human-like text so convincingly that researchers have developed special tools just to detect whether text was written by AI.",
    "GPT-4 passed the bar exam with a score in the top 10% of test takers, despite never attending law school.",
    "AI language models can write poetry, screenplays, and even entire novels, though the quality still varies widely.",
    "Some AI models can understand and generate code in dozens of programming languages, acting as a coding assistant for developers.",
    "AI can analyze the sentiment of millions of social media posts in seconds, determining whether the overall mood is positive, negative, or neutral.",

    // AI Records and Achievements
    "An AI system called Libratus beat four of the world's top professional poker players in a 20-day Texas Hold'em tournament in 2017.",
    "AI has composed music that was performed by a full orchestra and fooled audiences into thinking it was composed by a human.",
    "Google's AI once taught itself to play 49 different Atari games at superhuman levels using only the raw pixel data from the screen.",
    "In 2023, an AI-generated song mimicking Drake and The Weeknd went viral and racked up millions of streams before being removed.",
    "AI holds the record for the fastest-ever protein structure prediction, solving in minutes what used to take scientists years in the lab.",
    "An AI system beat the world's best Jeopardy! champions in 2011. IBM's Watson won over $77,000 against Ken Jennings and Brad Rutter.",

    // Fun and Surprising AI Capabilities
    "AI can predict what a person looks like based solely on their voice with surprising accuracy, using patterns in speech tied to physical features.",
    "There are AI models that can generate realistic human faces of people who have never existed, a technology known as deepfakes.",
    "AI can restore and colorize old black-and-white photographs, bringing historical images to life with realistic color.",
    "Some AI systems can read lips with about 93% accuracy, outperforming professional human lip readers.",
    "AI can compose a brand-new recipe by analyzing thousands of existing recipes, sometimes inventing ingredient combinations no chef has tried before.",
    "AI can generate realistic 3D models of objects from a single 2D photograph, a task that would take a human 3D artist hours.",
    "An AI once invented its own secret language during a negotiation task with another AI, which researchers had to shut down because they could not understand it.",
    "AI can predict the outcome of court cases with roughly 79% accuracy by analyzing the text of legal documents.",

    // AI and Animals/Nature Research
    "Scientists use AI to decode dolphin communication by analyzing thousands of hours of underwater recordings and matching sounds to behaviors.",
    "AI-powered camera traps can automatically identify wildlife species in photographs, helping conservationists track endangered animals across vast areas.",
    "Researchers trained an AI to translate honeybee waggle dances, revealing how bees communicate the exact location of flowers to their hive.",
    "AI can identify individual whales by their tail markings from satellite photos, making it possible to track whale populations across entire oceans.",
    "AI is being used to monitor deforestation in real time by analyzing satellite images and alerting authorities when illegal logging is detected.",
    "Scientists use AI to listen to coral reefs and determine their health by analyzing the sounds made by fish and crustaceans living there.",

    // AI Music and Video Generation
    "AI can now generate a full music track in any genre, complete with vocals, instruments, and mixing, in under a minute.",
    "OpenAI's Sora and similar AI models can generate realistic video clips from a simple text prompt, producing scenes that never actually happened.",
    "AI music tools can separate a song into its individual tracks like vocals, drums, bass, and guitar, even from a fully mixed recording.",
    "Some AI systems can clone a person's singing voice from just a few seconds of audio and then make that voice sing any song.",
    "AI has been used to finish unfinished symphonies by composers like Beethoven by learning their musical style and predicting how they would have continued.",
    "AI-generated background music is already being used in thousands of YouTube videos, podcasts, and advertisements worldwide.",

    // Famous AI Systems
    "IBM's Watson, famous for winning Jeopardy!, went on to be used in healthcare, helping doctors analyze medical records and suggest treatments.",
    "Tesla's Autopilot uses AI to process data from cameras and sensors to help cars drive semi-autonomously on highways.",
    "ChatGPT reached 100 million users in just two months after launch in late 2022, making it the fastest-growing consumer app in history at the time.",
    "Boston Dynamics' robot Atlas uses AI to perform backflips, parkour, and complex dance routines that would challenge even human athletes.",
    "DALL-E got its name by combining the artist Salvador Dali with the Pixar character WALL-E, reflecting its blend of art and technology.",
    "Google DeepMind's Gemini model can understand and reason across text, images, video, and audio all at the same time.",

    // AI Ethics and Society
    "AI hiring tools have been found to contain biases, sometimes unfairly screening out candidates based on gender, age, or ethnicity.",
    "Deepfake technology powered by AI can create fake videos of real people saying things they never actually said, raising serious concerns about misinformation.",
    "Some countries are using AI-powered surveillance systems with facial recognition that can track individuals across entire cities in real time.",
    "The European Union passed the AI Act, one of the world's first comprehensive laws specifically designed to regulate artificial intelligence.",
    "AI-generated misinformation is a growing concern, as AI can produce thousands of fake but realistic-looking news articles in minutes.",
    "Researchers are working on 'explainable AI' because most current AI models are black boxes, meaning even their creators cannot fully explain how they reach decisions.",

    // AI in Space Exploration
    "NASA uses AI to help rovers on Mars make their own driving decisions, since signals take up to 20 minutes to travel between Earth and Mars.",
    "AI helped discover new exoplanets by analyzing data from the Kepler space telescope, spotting patterns that human scientists had missed.",
    "SpaceX uses AI to autonomously land its Falcon 9 rocket boosters on drone ships in the ocean with pinpoint precision.",
    "AI is being trained to predict and detect asteroids that could pose a threat to Earth by scanning vast amounts of telescope data.",
    "AI aboard the International Space Station helps astronauts with tasks and experiments, acting like a voice-activated assistant in zero gravity.",

    // AI and Sports
    "AI analysis tools are used by nearly every major professional sports team to track player movements, optimize strategies, and prevent injuries.",
    "Hawk-Eye, the AI system used in tennis and cricket, can track a ball's trajectory with accuracy down to a few millimeters.",
    "AI can predict the likelihood of a player getting injured based on their training load, movement patterns, and biometric data.",
    "During the FIFA World Cup, AI-powered semi-automated offside technology can make offside calls in just seconds with centimeter-level accuracy.",
    "AI is used to generate automated sports highlights by detecting exciting moments like goals, dunks, and home runs from raw game footage.",
    "Some swimming teams use AI to analyze stroke technique frame by frame, finding tiny improvements invisible to the naked eye.",

    // Future of AI
    "Experts predict that AI could contribute up to 15.7 trillion dollars to the global economy by 2030, more than the current GDP of China.",
    "Artificial General Intelligence, or AGI, refers to a hypothetical AI that can perform any intellectual task a human can. No one has built it yet.",
    "Quantum computing combined with AI could solve problems in seconds that would take today's best supercomputers millions of years.",
    "Scientists are exploring brain-computer interfaces powered by AI that could let paralyzed people control devices with their thoughts alone.",
    "AI is expected to automate up to 30% of current work tasks by 2030, reshaping industries and creating entirely new types of jobs.",
    "Researchers are developing AI that can teach itself new skills without any human data, learning entirely through trial and error in simulated worlds.",
    "The concept of 'AI alignment' focuses on making sure future powerful AI systems share human values and goals, which many researchers consider the most important challenge in the field."
];
